import scala.annotation.tailrec
import scala.collection.mutable

object Week1 extends App {
  def patternCount(text: String, pattern: String): Int = {
    val patternLength = pattern.length
    @tailrec
    def patternCountImpl(text: String, result: Int): Int =
      if (text.length < patternLength) result
      else patternCountImpl(text.substring(1), if (text.substring(0, patternLength) == pattern) result + 1 else result)
    patternCountImpl(text, 0)
  }

  def frequentWords(text: String, k: Int) = {
    var maxCount = 0
    val count = new Array[Int](text.length - k + 1)
    for (i <- 0 to (text.length - k)) {
      val pattern = text.substring(i, i + k)
      count(i) = patternCount(text.substring(i), pattern) // we can skip the first i positions
      maxCount = Math.max(maxCount, count(i))
    }
    //println(count.mkString(" "))
    val frequentPatterns = mutable.Set.empty[String]
    for (i <- 0 to (text.length - k)) {
      if (count(i) == maxCount) {
        frequentPatterns += text.substring(i, i + k)
      }
    }
    //println(maxCount)
    frequentPatterns
  }

  def frequentWordsMap(text: String, k: Int): Set[String] = {
    var maxCount = 0
    val frequency = mutable.Map.empty[String, Int]
    for (i <- 0 to (text.length - k)) {
      val pattern = text.substring(i, i + k)
      var updatedFrequency = 1
      if (frequency.contains(pattern)) {
        updatedFrequency = frequency(pattern) + 1
      }
      frequency += pattern -> updatedFrequency
      maxCount = Math.max(maxCount, updatedFrequency)
    }
    //println(frequency)
    val frequentPatterns = mutable.Set.empty[String]
    for ((key, value) <- frequency) {
      if (value == maxCount) {
        frequentPatterns += key
      }
    }
    //println(maxCount)
    collection.immutable.Set[String](frequentPatterns.toArray: _*)
  }

  def reverseComplement(text: String): String = {
    def complement(p: Char): Char = p match {
      case 'A' => 'T'
      case 'T' => 'A'
      case 'G' => 'C'
      case 'C' => 'G'
    }
    @tailrec
    def reverseComplementImpl(text: String, result: List[Char]): String =
      if (text.isEmpty) result.mkString
      else reverseComplementImpl(text.tail, complement(text.head) :: result)
    reverseComplementImpl(text, Nil)
  }

  def findPattern(text: String, pattern: String): List[Int] = {
    @tailrec
    def findPatternImpl(text: String, offset: Int, result: List[Int]): List[Int] = {
      val index = text.indexOf(pattern)
      if (index < 0) result
      else findPatternImpl(text.substring(index + 1), offset + index + 1, result :+ (offset + index))
    }
    findPatternImpl(text, 0, Nil)
  }

  def findClumps(text: String, k: Int, L: Int, t: Int) = {
    def findFrequent(text: String): Iterable[String] = {
      val frequencies = mutable.Map.empty[String, Int]
      for (i <- 0 to (text.length - k)) {
        val pattern = text.substring(i, i + k)
        var updatedFrequency = 1
        if (frequencies.contains(pattern)) {
          updatedFrequency = frequencies(pattern) + 1
        }
        frequencies += pattern -> updatedFrequency
      }
      val result = frequencies.filter(_._2 >= t).keys
      //println(result.m)
      result
    }
    val result = mutable.Set.empty[String]
    for (i <- 0 to (text.length - L)) {
      //result ++= findFrequent(text.substring(i, i + L))
      findFrequent(text.substring(i, i + L)).foreach(pattern =>
        if (!result.contains(pattern)) {
          result += pattern
          //println(/*result.size + " " + */ pattern)
        }
      )
    }
    result
  }

  private def numeric(p: Char): Int = p match {
    case 'A' => 0
    case 'C' => 1
    case 'G' => 2
    case 'T' => 3
  }

  lazy val CONVERTION = Vector('A', 'C', 'G', 'T')

  private def alpha(i: Int): Char = CONVERTION(i)

  private def patternToNumber(pattern: String): Int = {
    @tailrec def patternToNumberImpl(pattern: String, result: Int): Int = {
      if (pattern.length == 0) result
      else patternToNumberImpl(pattern.tail, numeric(pattern.head) + (result * 4))
    }
    patternToNumberImpl(pattern, 0)
  }

  private def numberToPattern(n: Int, l: Int): String = {
    @tailrec def numberToPatternImpl(n: Int, result: List[Char]): String = {
      if (result.length == l) result.mkString
      else numberToPatternImpl(n / 4, alpha(n % 4) :: result)
    }
    numberToPatternImpl(n, Nil)
  }

  def computeFrequencies(text: String, k: Int): Array[Int] = {
    val frequencies = new Array[Int](Math.pow(4, k).toInt)
    for (i <- 0 to (text.length - k)) {
      val pattern = text.substring(i, i + k)
      frequencies(patternToNumber(pattern)) += 1
    }
    frequencies
  }

  def fastFrequentWords(text: String, k: Int): Set[String] = {
    val frequencies = computeFrequencies(text, k)
    val max = frequencies.reduce(Math.max)
    //println(max)
    for {
      i <- (0 until Math.pow(4, k).toInt).toSet
      if frequencies(i) == max
    } yield numberToPattern(i, k)
  }

  def fastFindClumps(text: String, k: Int, L: Int, t: Int) = {
    val clump = new Array[Boolean](Math.pow(4, k).toInt)
    val result = mutable.Set.empty[String]
    for (i <- 0 to (text.length - L)) {
      val frequencies = computeFrequencies(text.substring(i, i + L), k)
      for (i <- 0 until frequencies.length) {
        if ((frequencies(i) >= t) && !clump(i)) {
          clump(i) = true
          val pattern = numberToPattern(i, k)
          result += pattern
          println(result.size + " " + pattern)
        }
      }
    }
    result
  }

  def superFastFindClumps(text: String, k: Int, L: Int, t: Int) = {
    def findFrequencies(text: String): mutable.Map[String, Int] = {
      val frequencies = mutable.Map.empty[String, Int]
      for (i <- 0 to (text.length - k)) {
        val pattern = text.substring(i, i + k)
        var updatedFrequency = 1
        if (frequencies.contains(pattern)) {
          updatedFrequency = frequencies(pattern) + 1
        }
        frequencies += pattern -> updatedFrequency
      }
      frequencies
    }
    def updateFrequencies(drop: String, add: String, frequencies: mutable.Map[String, Int], result: mutable.Set[String]) = {
      if (drop != add) {
        if (frequencies.contains(drop)) {
          val newFrequency = frequencies(drop) - 1
          if (newFrequency == 0) {
            frequencies.remove(drop)
          } else {
            frequencies += drop -> newFrequency
          }
        }
        var newFrequency = 1
        newFrequency += frequencies.getOrElse(add, 0)
        frequencies += add -> newFrequency
        if ((newFrequency >= t) && !result.contains(add)) {
          result += add
          //println(/*result.size + " " + */ add)
        }
      }
    }

    val frequencies = findFrequencies(text.substring(0, L))
    val result = mutable.Set.empty[String]
    frequencies.filter(_._2 >= t).keys.foreach(pattern =>
      if (!result.contains(pattern)) {
        result += pattern
        println(/*result.size + " " + */ pattern)
      }
    )
    for (i <- 0 until (text.length - L)) {
      updateFrequencies(text.substring(i, i + k), text.substring(i + L - k + 1, i + L + 1), frequencies, result)
    }
    result
  }

  def skew(text: String) = {
    def weight(p: Char) = p match {
      case 'C' => -1
      case 'G' => 1
      case _ => 0
    }
    val result = new Array[Int](text.length + 1)
    result(0) = 0
    for (i <- 1 to text.length) {
      result(i) = result(i - 1) + weight(text(i - 1))
    }
    result
  }

  def xSkew(op: (Int, Int) => Int)(text: String) = {
    val s = skew(text)
    val m = s.reduce(op)
    for {
      i <- 0 until s.length
      if s(i) == m
    } yield i
  }

  val minSkew = xSkew(Math.min) _
  val maxSkew = xSkew(Math.max) _

  // O(k)
  def hammingDistance(l: String, r: String) = {
    @tailrec def hammingDistanceImpl(l: String, r: String, d: Int): Int =
      if (l.isEmpty) d
      else hammingDistanceImpl(l.tail, r.tail, d + (if (l.head == r.head) 0 else 1))
    hammingDistanceImpl(l, r, 0)
  }

  def findApproxPattern(text: String, pattern: String, d: Int): List[Int] = {
    @tailrec def findApproxPatternImpl(text: String, offset: Int, result: List[Int]): List[Int] =
      if (text.length < pattern.length) result
      else {
        val currentD = hammingDistance(text.substring(0, pattern.length), pattern)
        findApproxPatternImpl(text.tail, offset + 1, if (currentD <= d) result :+ offset else result)
      }
    findApproxPatternImpl(text, 0, Nil)
  }

  // O(n.k)
  def countApproxPattern(text: String, pattern: String, d: Int): Int = {
    @tailrec def countApproxPatternImpl(text: String, count: Int): Int =
      if (text.length < pattern.length) count
      else {
        val currentD = hammingDistance(text.substring(0, pattern.length), pattern)
        countApproxPatternImpl(text.tail, if (currentD <= d) count + 1 else count)
      }
    countApproxPatternImpl(text, 0)
  }

  def neighbours(pattern: String, d: Int): Set[String] = {
    if (d == 0) Set(pattern)
    else if (pattern.length == 1) Set("A", "C", "G", "T")
    else {
      val neighbourhood = mutable.Set.empty[String]
      val tailNeighbours = neighbours(pattern.tail, d)
      tailNeighbours.foreach { aTailNeighbour =>
        if (hammingDistance(pattern.tail, aTailNeighbour) < d)
          neighbourhood ++= Set("A", "C", "G", "T").map(_ + aTailNeighbour)
        else
          neighbourhood += pattern.head + aTailNeighbour
      }
      neighbourhood.toSet
    }
  }

  private def mostFrequentApproxPatternsImpl(text: String, k: Int, d: Int, countFunction: (String, String, Int) => Int) = {
    var maxCount = 0
    val hood = mutable.Set.empty[String]
    for (i <- 0 to (text.length - k)) {
      val pattern = text.substring(i, i + k)
      val n =  neighbours(pattern, d)
      hood ++= n
    }
    val frequencies = mutable.Map.empty[String, Int]
    hood.foreach { pattern =>
      val countApprox = countFunction(text, pattern, d)
      maxCount = Math.max(maxCount, countApprox)
      frequencies += pattern -> countApprox
    }
    frequencies.filter(_._2 == maxCount).keySet
  }

  def mostFrequentApproxPatterns(text: String, k: Int, d: Int) = mostFrequentApproxPatternsImpl(text, k, d, countApproxPattern)

  private def countApproxPatternAndComplementPattern(text: String, pattern: String, d: Int): Int = countApproxPattern(text, pattern, d) + countApproxPattern(text, reverseComplement(pattern), d)

  def mostFrequentWithComplementApproxPatterns(text: String, k: Int, d: Int) = mostFrequentApproxPatternsImpl(text, k, d, countApproxPatternAndComplementPattern)

  //  val text = "CCGGGGACATCGTCAATCCATCCACTGTCTTTAAGTTGACCTAGACCTGAACAACGCAGATTGGGATAAGTAAGCCAATAGGCGTTCTTATGAAGATCTACAAAGGATCCGGTACCTTTCCCGAGTGAAGACCCTCCTTTACCTAACCGGGGTCAAAGTCATGTACTCCACCCGAACTTGACCTACTACCGAACTTTGATCTTGGTTAACAACGCCCGAGCGCAAGATCTAGTGACCGGACCGGGTCTAGACTACTTGACCATAGGCGTCTCTCTGTCAGCACGGGAACATAGCTGTTTGGAGGGACTCTTCCACGTTAAATAGCGACGTTGGCCGTCCCCTTCTAGTTGGCGACGCAACTAGCTCATTGCCGGAGAAAACACCCCTGGAAGTTAAGAGGGCACAGTTCCCGACCTAGAACGAATTTTAGATGAAACAGGGCCTCTATCACGTGAGAACCTCGCAGATTATAAACACATTTAAATAGGACCTTTTGAGGAACAGTGTCTCCCTGGTTAGACGACGATAGAGATACGAGTTGGCTGAGTGACCATGGTGGAATGAGCAGACTACTCTTTAATCGTTACACCCTCCGAAAAGTAACAGTATGACCCGCAACGTTCTCAGGGGTAGTGCGGGAGGGTTGTCCTGAGTCTTACTTTGGTGTCAGCAATCCTTCGCTATCCTCGTTATGCACCTTATCATATATGGT"
  //  val k = 6
  //  println(computeFrequencies(text, k).mkString(" "))


//    val text = Source.fromFile("src/main/resources/EColi.txt").mkString
//    val k = 9
//    val L = 500
//    val t = 3
//  //  val clumpedPatterns = findClumps(text, k, L, t)
//  //  val clumpedPatterns = fastFindClumps(text, k, L, t)
//    val clumpedPatterns = superFastFindClumps(text, k, L, t)
//    println(s"Found ${clumpedPatterns.size} patterns:\n" + clumpedPatterns.mkString(" "))

  ////  val text = "TAAAGACTGCCGAGAGGCCAACACGAGTGCTAGAACGAGGGGCGTAAACGCGGGTCCGAT"
  //  val text = Source.fromFile("src/main/resources/EColi.txt").mkString
  //  //println(skew(text).mkString(" "))
  //  println(minSkew(text).mkString(" "))

  //  val l = "CCCGGCCGTAACGGGAGGAAGTGACGCGTTGCCCAACTTACATCGTTGTTGAATCACCGGGCTGTGACCACACGTTAGGAACCGGGTCCCATGAGCTGCCTAGAGTACGACATGGCTTCCACGCTGAGTAAACGAGGCAGCAACCTTTCCCCCGGCTACCGCGCCGACCGTTCCTGATCATAAAGTCAGTGCATGCTTAAGTCTATCAAGCATGCTTAAGTAACTTGCATTCCACGTTGATAGTCCAAAGCCGTGTCATCCTTCTCATCTCATTAGGCGTAGCTTTAAGGGTGATCGTGGTGAGATGAATACTTGGGAGGGCTCATAATAGTTCGGTCCCTTCGTCTTTGAGTGCACCCCCCATCTTGAAAGATAGATCCAAGCCTAGTCAGTGAAGTGTAGTCCGATTTGCAAGCGGAGCAACGTCAACAACCGGGAGGCAGCGCGCGGCGTCATTGTAATTCATTTAAACTCACCATACGAATCTACTCCCTGTCAATGAGAAAGCTGTGGCAAGGACACGCTTTGTTTGCGTTGTTTGGACGACCTGGTGAGTTCGCATTTTACCAGTTTTCCTCAGCAACTATCGGAGCGAGATCGTACCCCTGGAATATGCCCTATGGATTTACATACTGGTACTGCAATCTCTTGTAGCAACTACTTAGACGGATAGAAGCTGCCTCAGTCCATATCATTTCCGCCTGGGATCAGGGATCCTGCATGCGGAAGTCGTGAGCCAGTCGAGTATCTCAGGTTCTCGGTCTACGGGCGGGATAGGGCCAAGGAAATCGGCAACACATAGGGGATATTTATTGTGCACGCAGAAGAAGGACATCGGATAACTTCCAGGTCCGCGCAGCTTAATGCGGGCGCGCTGGCACGATATGTTTTGAGGCCCTAAAATCGGATACCCATAATCCGATAGCTCTACCCGGTGATCGAACCGTTTGTTATCTCCTGCTAAACCCGCTGCTATCCCTTTGGGGCTGGTTACTTCCTTAAATCTACGTTCACTGCTCGTTACTATAAGTTTCCGGCAGGAATTGTACAGTATAAAGGTGTAGCTGGCGCAGTTGTTGTTTATGCCACAAGCAAGTGCAAGGGTAATCGACGTAGAGTTATATCAGACATTTCCAGCCGCGCATCCTCATCACTATGGTATTGGTATAGGAAAT"
  //  val r = "CCGGACTCACGCGAGCAATTTCAACGCCATACGCACAATCTGCAAGGAGTATCGGTCTAAAGTCGAGATTGCTCGAAATGAAGGGAAAGGAACAGCTAGCTTTGCAGGACGCATCGTGCTTGTGCCAAGATTAGGCTATGGTGCTACTGACGAGGACATCATAGTCTCTGCTACGTGGGGCGGGTGGCATGGCGTTAATCGTTATAAAACGGAGTCAATGCACTGAGAATAGACCTGACACGCGTTGCATGACCAGTCTGCTCATGGAATAATCCTTACGAGATGGAGTTGCCTATCGTCATACCCCATCAAACGGCGTCCGCCCAGATTCGGACTTTGATGCATGTGCCGCGCCATTCCGAGGTATATAGGAGTGAATCGAGACGGTTCCCACGTGAGCATAGGATGAACTCCCAACATTGTGAATCGACCTATTCGCCAGCTAGATTCATAACAGGTCCACTACAGGATCGCCTCCGTGTATCGGTAAAGATAAGTAATCAGCCTAGAGCAATACACATGCATGACTACTCTTAACCCTGATTTGAACGCGTAAGTCGAGGTGCGGTTTTTAAACCTAAAGGGTGGTGAGTCACCTGCCAGTCGTAATCTAGTTCTGATGCCACAAGGCGATTTGTTCGCATTCGGGATTAGCATTAGCGGTAACTCCAGTGCCCGGCCGTAGCTGGGCGGACAGGGCGGAATGCCGAAGCTAAACTAAGGGGCCGTTAGCCCAGTAGCAATCATGGAATCTCGTTCGGTGCAGCAGCGCAGTTGACGTATGGAACCACACCTCTCAATCGAGCGAATACGACATCAACAATCTATAACGAATCGAAAGGGTAGCTGAAGAGGGCACATATGCCCCGAAAAAGACCTCGGGATTTTATTAAATTCCTGCGGCTGATGACAATCCAACCCCCATGTGGATTTTGAATGCTAGACCACTTAATGCTAATTTACTCGTCTAACTATCCCAGTGCATACTGAGCCGAAGTCACGCCTGAATGTTGCCGCAACTCAGCACATCACTAACGGTGCAATAATGCCTGGTCGAACACAAGAGCAGGGCACCCACCAACACGCCTACTTTGCGCTAGGAGTCAGCAACCTACAATGGCCTCATGAGAAGATAGTCGCCTTGGTACGCGAGTTCTTGACTTTGTCCTTTAATA"
  //  println(s"HammingDistance($l,$r) = ${hammingDistance(l,r)}")

  //  val text = "TTTTGTGACGCTCGTCATCGCTCATCAAAACCTGAGTGCCAGACGGACGGCAGGGCGCGCGCGCAGTTGCCTGAAGTCTTTGCTTCTCATACTCAAAAAATGCCTCACTATGAACACTGTTTTATCAACGGTATAGGTCTCTGACAGGCGCGATGGGCGAATATAGTGCGCGGGCCGGACTTGTCTTACTCAGGCATCCGGTTATCTTATTAAGCATAACGAGCAGACCAGGACTCCTGGTGCGGAATAGATTAGAAAGTACAAAATGTTGAGAAATACCAGTCTGACAACATATCGCGTCGGGCAGCCTAACATGAGCTACGCTTAGGTCACCTAGGAGGTCTAACTCCCGACTGGTCTACACGAGGTTTGGCTTCACATAGCAAAACGGGTGATCGTAAGCGATTTATCGCTATCATGGTACCGGCTGGCGCGGTTAGACTATAGCCCGGTCAACGTTTTCCAACACCACTGGCTCGCTGACTGCCGACGATCCACGAAGCTCATCAACCTAGCTGGAATCAGTCGAAGAAACGTATTACCCAGATGACAATATCCTTTAGTTACGCGCTCAGTTATACTGATCGATTTCGACTAACTTGGCAACAAAATGCCGTGCTATGACCCCTGTTCTCGGTAGGATCATAGATGATAGTGCGAATAGCACCGCCTACCATGCCAAGGACGATGGATTGTGGCGACCTTAATCGTGCTCTCTCGACGTATTCTGAAAAGGGCCTAAGTTCTCAGTTACCCCTCCGGTATCATCCTCGTTACTCCTTCACTCGCGGGTGAAGGGTAAAGCAATCAGCAAGCGGTCGTTTATCGAAGCAAGCTTGGTAGAGGTAGCATGCCCCATGCATACAGAGTAAAATAGTCGGCAATCAGTAAGGGGCAAGTCTCAGCAATCTCAGAGCCACGGGTAGGTGATACCTCAGTAGGCCGATCGAGATCGTGAGATCCGATATCAGGGTGTCCTTAGAAAGTTCCATGCGCTGTTCCGTAGGCGGTGACACTGCTGGCGTCATCTGCCTTTATCATCAGACTCTCTTTCAGTCGGCTGTCTGACTTGGCCCCGGCTCTAATGCACATCACTCGATTGGCTGACAGTCAAGTAATAAGTTGCCTATCCCGTGCTAGTTGAGAGCCCTTTATCATCAACTCAGCTGCCTGGCCGAACGGCAATTTCCGCACGGTAGTAGTCGCAGATCAAAATCGCGTCGTCAACCCTATGACCCGTTTACGAGTGTGAGGGATACGACGGCTATTCTTGCCCTAAGGTTTCAGTTCAATCCCTTATTTCGAGAACGACTAATCTTGCCACTCGGGGGGGGCGGCCGGTAAGGAGTTTCGCCCAATGGCGCCCGCCTGCCCGAACGTCAGACGATCAGCCCCGCAACCGCGTGTCACACAATCTGGTCTTCAGAGCTCATTTCGTAACTAGGTATCGCTTTCAAGTATTGGAGAAACGCTGTGAGCTGAATTTCGTACCAGCTTGTAACTCCCATAGTCAGGGGATAACTACGTCCCAGTTTCTACCGTAGCTTTATCCTCATTCCGGCAAACGTTTGACGCATTCAATCAACAGTACGTCAAGCGTATGATTATCTCCTTAGTCAGTTTTATAGAATAGATTTTACTCAGGGGCTGGGCACGTAAGAACACTCTCGGTCGACCTTGAGAGTTTGGATGTGCATTAACCGTGGCTATCTCACGCCGCTAGGGAGACCGCTATCAATGGTATAAACCAGTGATCGCGCAGCGTCCCGCGACAAGCAACTACAATACTCTATAGCTATCAGGAAAGCTGAAATTTTGTCTTGGTCGTCCATCAAGACCGTGAGCATGTAAATCACTCGCCAATTCGCAGATAGGAAATCGTGCGAGATCGTAAGGGCCGATGAGAATAACGTTTAAAATGTGTGAATCACTGCATGGCCCAAAATCCTGGCTGGGTAGACTACGTGGCCGCAAACAATGGGAGCGGCACGATCGTGTAGGTCGACTGGATGCGTACGTGAGTGTGTGGACCTCCGGTTAAGCACCAGATCACGTGACGCTGCGTGCCGTCTGCAGCCTCCCAGCTGCTGGCACTGGCTATACATCAGGAGAGTGTAGAGGACCACCTAAATATCCTCATTGTTAGCCTTGGTGCGCGCCAGACGTAAGTATAAACCCACGCTAAACGGATGTGGTGGGGTTGTAAGCCATACCGCGTTACCCGCACTAGGTTTAAATTATGATCGAACACGAGTCTTCTCACGACTAACAAGACCGTCCGGCACCATTAACGACATGAAACAAGTAACGAGTGAAGCCCCAGTTCACCTCGGGAACCGACTGTGCTTTCATCTGTCAAGTATCGCGATGAGTAAGTAGAGGCTCCATGATATCCAGTCCGTTTATATGAGGGGAGTGCCTGAAATCCTAGTTACCATTCCTGTCGGTCTGCCCGCTCTTTTACACGCATGACTGGTCGCGGGACTTGACTGCTGAGTCAGTGAACATAATGTGATCAACGGCCTTAGTGGCTAAGAAAACTGAACCTGGCTCATCAGGACGCTACGTGGTAATTGCAAGTACAGGTATATCCCATCCCTCCTTGCCGGCCACCGTATTCAGAAAAATGCCTGACACTACCGAAGCGCGGCCGCACGTAATCGGTCACCAAACCGGCCTCTCGCGAGATCCAGGCGTTACTAGACAGGGAACCTGCCGTGGAGCACAGATTGCTGCTGGCCTATTGAGGGAAGGGAGCCCGCATTGAAAACGTTTCCTTGTTTCCCACTCACGGGCAACCCCGGAGAAAGACGGGGGCGTCCTGGAGGCTAGGGGTTATTTTGTTATCTGGATGAACAAACGGGATGTAAATGGCTTTGAAACGACAACCGAGTGAGTATGTCAAACCAGCTGATGGATCGGTAGAAGTAACTGGCTCGGTTGTCCGAGTTCACCAACGAGGACAAATTACTAAGAGTCAGCGTGGAGGTACTAGTATTCGATATAAAATCAATGCATAATGACGGGAGGATATGGGTAAGCCGGTAATCGACTTGTGCCTGTGAAGACTAGAGACGAAGTGGCTTGGTGTTATTCTCTCCTCTTAAATTGGGCCTGCTTGACCAACTGAAATGTTCGGCTTTTTCCAACTCAATAGCTGTGCGGCTCCACCGGATAAATCTAATCCTAAGCCATAGGACGGGCTAGGTTCCGCCAACCCTAGATGAACGACTCAGAATCCCAGTCTTTGGACTGCCGAAGCTAGCGATACACCCTTTAGGGCTCAATTAGAGGCTGGGCGCCTCACGAGAAACGAATCTGGATACCTTCTCTCTGTTGGTCCACGTGAAGCATCCGTATATGCCTTCTCAAAATACGTCTTTCACGGATTTAGCAGAGCTCTCTTAAAGCGCGGATCGCCTTAGATGGCGCAGCTGACAGACAAGGTAGATCGAGGAAAGTTCGGGCTGTATTGAGGTTTAAAACCACTCAGTGAGCCAAGGCTTACAGTACGCTCCCCGCATATAACCAATAGCCTTTTTTTAAGCAGCGTCTTGCACCTTTCCTGCTGCGCTGTCTTCAAGAGGTGCCCATTCTTGAGCGGGCAACATCGGTGTCTCCCGGACCTTTCGCCTGTCCGGGTTTCTTTTAGCAGCCGCGGATCTAGGCCACCGTGCCGGCTTGCAGGTAGCGATGTTGACCTAACCCCTACCTCTTATACCGATATCTTTATATGCCTCTAGAAAGATGCGGGTCCCCAAAACCCTTTAGGCAAAATCGCCGCATTACTGGAAATTTTCGGTCTAAGGAACACCGAATTGGGAGGGAGGGAGGTCACCAGAGTGGTCACATGAACCAGTGGTAAATCAGATCCCCGCGTTTGGTCGTTATGAAGATTCCCGCAAAAATCCCTGCAAGCGATATGTTTGTTTATTCGGGGCGCAGTAGATAATGGTGCGCCGAGGCACGGAGATATTCGTCTAATTACCTTAAAAATCCGTCCGGGTTACCGGAGGACGCGGAGTACCGGGCATCCACCGGGGAATGTGTCCGGCTTTCACGGTTATCCGATAATTTAGCCTCATTTTACCAGCAAAGAAGACCCTATATCACTCAGCCTTGTTAAGCGAACAAGGCCTACAATTTACGCAAAGCTACGTAACCCGCGACCTGCATCGCGGATTGACTCCGATATACATGAGATATTATGGTTGCAACACCTGGTCTATAAAACCAAGACCACTACTGACCGTCCATCCTGTACGAGGGCCAGCGGGAGCCGTTTCAATGGGAGGCGTGGTTAATTCGACGAATTGTGCACGAACTTCTCTCGTTACCGGTCTCAGGGCACCAATGAATCTTCTCATTCTACAACTTCGCAGAAGATCAGAGGCAAAGTGTTATTTCCTCCATGGCCAGGTACATCGGGAAGCAGGGCAAGTGCCAGGTGCCCAGCTGCTATTTCCATTATTGAAAGAATAGCAGAACTCGAGAAGCCACGACCCAATTTGGCTTCTAAGTGAGACCTTACTGACTATTGCGACTTGTAAGGACACTAGCCTGAGTTGATCGAGTCTATTTAGTTTACCACCGCCGCCCCCTAGCACGCGTGCTGGGGATTGTGTCATGCCGTCTGTTGAACAGACTCCGTGACAAAACAGTGAAAGGGTTTTCACCCTACCTTTAATTACGTGTGTAGCGGGCCCGATTGAACTAGGCTGGCTACACATCCATACATGATCTCAGAGTGTGGTACCTCACCACATTGTACCGTACTGTCATTGACCTCTGCGGGAGACTCTTCGACCCTACATTCCATGGGCGACGTACCCAGTGTTGGCGGGAGGTGTCCGTCGGTTCCTGGGGGGTGGGCTGCACACCCGAGTCGAGTACTTTACATTTCGGCAAACGGAAGCAAAGAAATTAGAGTCCCAACCCTTCGCCTGTTTCCAATATTCCTCTATCTCGCAAAACGGAAGTTGTAGAGGAAAGCGTAGAGTTGACGACTCAACAGCTTTTTTAGCCGGAACTGGGTCGCCATAGGCCTTAAAGGTCACGCCGCCTTCCTGTACTGATCAGTGCGATTTTTTAGACGCGAAAGTAAGTGATTGACATCACGCGCGAAACTGTCATTCAGACATATGAAGTGCGCGTACGGTGAAGGACGCTTCCTCTTCACCATCACTACAGCGCAGCCGGCCGTTGTAACTTAGTCGAGCAGACCAGCTTCGAGCCACTAACCGGTAAGAACGTTTTATAAGATAATAGTCCTTTTCTTGGGCAACCTACAAACCACTTTTTGCGATGCACATCGTAACAGCATGTGCTATTCCGTGCCCTATACTTTCCACAGAGAGTCCATTTCCAACGTTAGTACTGTAGTGGTATTGACTGATAAGATGCACATATCTGCCTCTGGCAGCGGGGCCTGGTATTCCCATTACAATGATCGAATATTTAAGGCTATTTAAGTCCAGAGTTTGGCAGCGGATTACAGACAACCCCCCCGAGAGCTTGCCCATTGTTGTCGCATCTCCAATTATTCGCAGAGGTCACCTGCTAGAGCGACTTAGTATTGAATGGGTTAAATACCGGGTGCATTATCCAGCTCTAGCCCACGCACTGGCCCTACCCGCTACCTTTAGTGCATGGCTGGGGAAATCATTACTCACCTCGGAGAATTCATGTGGGTGGTACCATCAATAATGGGTATTTCGTCTTCCGAGCAGCGTCTGGCCTGCAGCGGTGGACGGTAGCCGAAGTGAGGGATTAGCGCATCCACCCTGTATTACCTCCGCCTGGAATAGAGCTCATGGCGGCCCGTATCGCGTGATTAAATGGCCGATTAGGAGGATTACGGTAATTACATCGAATCCACAACGCTGCCTTGTCTGCAGCGATTGGCCCGCAGTACTTGCGACCATGCAATCGCGCGCTAATCTACCCCTCGTGCAACACTCAAATGCGTGGTCATGTATGTAACCTATTCTGATTACGCCGTGGCCTGCCCAGACGGCAGTAGCGTCCCAAGGCGCACACCTTTTGCTAGCTCATCCTCGGGGTTGGTAACGTCCACGGAGGCGTGTCTCTCCACCCCGACCCATCGGTCCCTAAGCTAAACTTTACTTAGCGCGCTGTCCGGCTTAAACCCGAGAGCAAGCGGTTCAGGAGCGAACAGGCTAAGATGTCGTATATCCATTGCCCCAGATGTAATCGTCTTGGAAGTTCGAGTAGTCCTAGTTCTCGTACACTTCTGCACCTCGGAACGAGGCCTCCAATTGCTAGCGGTGTTCCTCCGTTCGTGGATAGCTGGCTTCCTAGTCTACCTGTAAGTTTGGTCTCGCACGCAACAGAGTGTCGACGTGTCGTGTTACCTTCCCACGTCCGATCACGCCTCGCCAACTTCATGTGCGCATCGCGGAGGCGGGGGCAAAGTGGTGGCGATCCACCAGGTATAAACGTTTGCTTCAGGCTTACCCGTGGGTCAGATCGGACATGTCTCGTGGCATAAAGCCCTCTCAACTAAGAATACGTCCTCTTAAGGCGAAAGAACATCAAGAACCTCGACCTCACCTGTGGTGGTGGTGCAGACTTGGTCGGAACAGTGTCTAGTCTCCCTATGCTACGTATTCTGCCATCACGGGGTCTCGAGGGATGGACCAACGAACCCATAATATATGGTGATCACCGTAGGATCGAACTCGCACACTAAAATTGGGATCACTAACACCTATGGTAGTAGTGTAGTGAAACTGAGGAAGCTAGAGATCTGCCAAGACAGAAAGGACCTTCTGCGAAAAAGAGCGAGATAGAGTATGGTCATTTCTCTCTTTTATGCTATTGACGATTATGGGAGGACGATGCCAGTTTATCGGAGCGCTGCAATCGAATTTCGATCCAAGATCTCAGAACCAAACAGCTACCACCGCACACAAGACCGCCCTTGTTACAATTCGTTCGGTGCTGAGGACTAGGTGCAGCTGGCGCCCTTTGAGTTACATGCAACCCGGAATACCCATGGCCACGCTATCACATACGGCATACCCACTGGCACAGCCAACTCCAAATGCTCTGTGAGTTGCAGGCTTCGTCAGTTATGTCCGGAGTCAAGTACTGACCCCCGAGAAAGCGGAAGTCGACTCTTAGTGCCGGATGGTCGCTGCACTCCAACTGAGTTGGCTAGCTCATGAGATTGTCCATCCATAAAGCGTTACACTTATTGCCGGGACATGAAGAGGTAGCGTGTGTATCCTCATCACGGCGGGAGATCGAGAGCAACAGTTGTAACACATAGTAGCACTAGACTGCCAAATAGGATACCCGAACGCCCTACCCAGTAAGTTGTAATAACCGTTGATTAATCCGCGATGGCTGTTGCCTAGGCCAGGGGTATGGAGACCTTTGTGGCCGACCTGACAATAATTCCAGGCCGCTTCTGGAGAGTTACTACCATCGCTCACCCTCCACACATGTACAGTGTTTGACGCTGGATCAGAGATCCGGCCCGCAAGTTTATAAAATTACAACTACACAACTCATACCTATGGGAAATAACCATTTCTCCAGCGCGGTTACGCGTGGATCAAAGTTTTCGTGCAGCTTCGTTCCAGATCCAATTCCGGCTAGATCCCACTGTGTCTTCAGAGTGAGGTCTGGGGTGTTGAGATAAGGCCGATAGGTAAAAGGTTTGTTTGATCTTAAGAGCTAAAACGGGTAAATTAGACTTTGCGATGTACGCGGCGCTGAACACGAGTTATAAAGAAGGTCGCCGTAGCCGCTGCGTAATACACGCGACAGGTCCTTTGAGCTGGACAGAGTGCGCTCGGATGGCGATTTGGCCTAATCGTCTGATGAGACTTAGTTCATGTTGATAGCCAGACCTGGTAGCGAGCGTTAAACCTACGGAAAGAGTTCATGTAGTACGGTCGCGTCGGTACTGACCCGTACCGATACACTGCTCACAGGCCTTTCAGTACTGGACACCGAAAATGATTAGGCCCGAAGGGTTGAGTAACTCGTCTGTTGCCTCTCATGGCCTTTACAGGAAAGTTCAGTTCAGCGGTTATCAAAGAACCTGCGTTAATCGTCAGACATGTTGCGGTCACGTCGCGCGTGTTAGTCATAATAAGGGTCTCGTGAGTGGATGCTAGCAGTTTGAGGAGTTGGTCCTCTGCCCCTAACGCGAGCTACCTGACTAATGCGAGTGACTACTTCGCCCCACCTAATGTGACGCGGGAACTTTGGCCGAGGAAGGGTTAGGATGTGGTCAGTACGAGACTGTTAATAACTACATGGAGATGATTGCGCTGATATCCAAGAACTATAGAGCTATTTCTTCCGCTGGTGGTATCGTCTTAAGAGGCAGGACAAAGTACATCCGCGATGTGTAAACCAAGTTTAACGAGAAACCTAGTCCACTAGGGTACAGCTAGGAACCAAGCGGGTAGGAATAATAGGGTCTCGTGTAGGCCAACTCGTCAGCTGCACGGGAGGGTATACGTAGGAATAACTTAAGAGGAGGCAGGCGATTCCTTTAAGCGCAGGATTCTCCCCCCCGGGGTAGTGAGGTTTGGCCCCTCTCCCCAAACATACAATATTTGACGGGTTAACTTCACATTATCGGAATATGGCGACCTAGAATAACCAAGAGTGGAGGAGCGATGGTATTGGGCGATGTACAGGCAACTTAATCACACCATGTTCCTCTAAGGAGCATGGACTGAGACGCGGGAAACTACACTTCGTCTCCAGGCCTTTGTGGTTTGTCCCCCCTTTTCGCCTCCAATCGGATGTAAACTGAGGTGAGCCGATTACACTTTTCTCGAGGCTACTAGTTAGTGCACCGAAGTGATGGCGTTTACCACGTGCGTATACTGGGCAACTGTGGGAGTCACTTCTACTAATCCCAAGAGCATGGCGGGCAGCCGTAGCCTAGCTCTTGCATCCCTGACCAGAGCCATGTCCGTATTTCGGTAGAAATGAGGCAGAGTATTTCGCAACTCCGTCCCCCATATTCTGTGGACAGAGATAAAAATATCCCGATACCCCTCCTCTAAGCTAGGCATTGAGTGACATGTGTAAGAGTTGTTCCTAATCCACCGGAGATCAGGTAGGGACAAAGGCCTCACAATGTCCCGTAAGTTGCTACCTGGTTCTCTCTTTCCGGAGCGTACCGCTTAATGACCGTATGGGAGAGTTTGCACGCTGGAGCGGACACGCACATATTCTGAGACCTATGAATGTATCAACTGTGCTTCTAAGACACCAATCTGAATCGATTGAGCGATCCAGCTTAAAGATAGCAGCCTTGCTTTGCATATTTAGACTAGGATTAATCCTGGGACGAGACATGTGGCAGGACGTTACGGCGAAGCCCCTCCCCAAAGCTTGGTGGACGACCTGATGACACAGAACATTTATATGGTTTCTGGCCTCCAGTGTTAACTTCAGTCTCACGCCACGATGATTCTCGGCAGCTTACACTCCCCTGAGTTGCTTATAATTAGCAGTGTAGGCTGCACTAGGGTATATACCGGAAGGGATCATTTTTTTCATGCACTTAGAAATTGGGATACCCATCGATCTGATGGGTTTCTTAGCACGCCTTATTGAACGACAGCTACGGGCTCACTCCGTCTATCCCGACTTCCCAGTGACTACCGCCGTGTCTACTGCCTGGGGATTCACACGTCCTAAATTGGATCTGTGGGACTATAAACCGACGATAGTTTATGGGACTGACAACATAGCCAGCACGTGATCGCCGCAAATATAGGTTTCGCTCTTGAGTCGAGCTAGCTTTGGGAAATCAAGGAGATCACGCCGCGTCTGCGCGCGCTCTCAATTGCTAACGGAGATCAACTTTCTATCTGGACTTGTTCCACCCATTAGCACTTGGCGCGAGAGCAGTGCAGGTCTGGACGGGTTCACCTTGTGCAGAACTTCTATTGCGAAGAGCACATACTCACTGAAGCCCCATCTAGGTCTCGCTGGTTAACTCGACCTATGGGCGGCTTTGTGAACCGCGGTGAGCTCTCTCAGCGTCGTAGGACGGTGTGGGCATGAGTAATGCCGCCATGCTCCTTTAGATTAGGAAGCTAGGGATTGCCAATCTCACCCTTAGGCGTGACCATGATTCTTGATGCGTATCAGGTCGTCCCTATCGTACTCAGGGCAAGGCCAGACCGTTTGACCTGGTGTGATCCGACTCGTTCCGCCGCGGCGCGACTGGGTGAGAACCGCAGGATAATAGCAGACTGTTTAATAAGTTTCAAAACAGGAAATTCCCACTGAGCGGTTTACAACAGGAACTCGAATAGTAAGAGTGGGACGCGATCAATAGGGGGAGTACGTTGAGCTCAGCCTCGTAATCACGAGTATTACCAAGAGTAGGCAAGGTCGAGTGTGTCGTTCTTTTATTCCGAAAACGGATTCAAGAGCCCCTTGCTAGTAAAACTTTCCTTTGGAGCTGCAGGCAGACCCGTTGACGACAAGCGCTTGACTTTGTTTTATCCATGCACTTACATACGTCCTCGGACTCAGACGTACGGCCCTTTTCTGCATCAGTTCTGGCTTTAGTGGCTAGGATAGAGCCACAGCTTAACACCAGCTATTGCACTAACCGGTAAGGCGAATGTTCTACTCATTTCAAAACTATATGTTGTGATGGCGCTGCATCCATTTAGCAATATGAAACTTCGACTATTGCGATCTCTATGCTAAGGGAGTTGTGACCGCAAAGGATGCATTAAAGGAATCGTTTAGACCGTTGGAGAACCGTGGCGATTCTAAGGAAACTACCTGTATCGAAACCCCCGAAACGTCTCTCATGATTGGTTGATTCTGGGCCTCGCGGCCTTTCAGCTAACGGCTTGGACTTTCTGGGACTTGAGGCAGTCCTGCAAAAGATATCATCGTACGTTTTCCGTGAATAGAGAGACGCTAAATTCTAAAAGAGCTACGTATATATACTCCAACGAGGTTACGCTGGGCCAGCCGATCCGGCATGAGTAAGTCATTGTTCTCTTAGACGACATTGTCGCGCGTTCGCCTAGATCAAACGCCAAGACCATTAAAGTCTTCATTCACTTTCCTCCGACTCCGGTCACAGCGCGAACTAGAGTGAAGGTGGGTGCTCGATGGATTGCCTCAGTAATGGCTCTGGGATCTGTGAGACTGCAGGCATTCAAGGCGTTTATTAGCTCGCGGGGGCCTGAGACGGGCGTCGGCCTGTGTAGCGTAGAAGACAGTTATATAATCGTGTATGAAATGCGTGAACCTGACAACCTAGCCGCGGAGGAGTGCTAGACTTATCACTGCCTTTCTCTGGCATTATTCCATTAAGTTGCAGCATTCGAGGCACACTAATTGTGAATGCGACTTAAGCACTATTGTAGGCCCAAAGTCGTTGGGAAGGTGGGGCCGGAACAGGCCGAACGCGGAACTGACTCCCGGATGCAGAGGTCAACTGCTCGACAACGGCATCCTTAGTGTTGTTTGGATCTGTAGCACCATCACTGGTCACCTTCAAGGTCCATTCTGATTGGGCAACTCGACCTAACTAGTAATGTACCCCATTCTCATCGAAACCCTATGGCGGTATCGGTGTCGAGGGGCTTGGGCTTCCCGCGGAGCATTCGTCGGGGGGGATAAACCAATAAGCGATTTGGTCCAAACCTCGAGTAGTCCTCAGGTAATGATAAGCTTGGTTTGAACCAGGGGCCTCCAGGCCTTAGGCAGACCATAGGCATCACGTATAAACCGGTGATACTTAAGTCAAACCATCTCATTAGCCTTCCTATAATGGCGGTACCAGGATGCCCAAGGCGATCTTAATCCAAAGGTATTATACTCGGACCATAATTGGTCTAGGCCGTATAATGACTGTAACATGCGCCGAGGGCGCAAGGCTTGCTTCCGGCGACGGAGATTCGCCCTTGTCCATAAGCCCAGCAGGATGGAGCGTGGACAGCATCGGACTCGTGGCGCTCCGTTAAGAATGTGACACCGGGGCTATCAAACTGTCTGTTGGAATCGAAATAACTAACGGGCCTTGTAACCCTACTAGACATGAACCGCTAGTGAATCACTTGAATCAGGCCCTTTTAAGTCCTAATTCGCCCTCTGTGTAAGGTCCATGGGTGACCTGAGCGTGGCCATATGCCCAAATAACTATATAGAGCATGTGCTCGTTGGATTTGTTTTTTTTCAGGCTGTAGATTTATGCCTGAGCGTGAGAATCTTAATCGTAGGTCAGGTAAGCTTTTATGACCACTTGCGTAATTGTCAAGCCCCCTGCGACATGCTTATGAAGAGCACTTCCAACAGCAAGTTTTTTACACTAGATAGCTGGCACCCACTAAGGTGGGACAAAATTAATTCCACACCTGTGACTGCAAGACTAGGGGCCCCTTCCATTCCACACCAACAAGCGATACAAAATCCTAGTGAATCCATGCTTACATTCAAAAAGACTACTTCGGTAGTGATTCCCTCTAGAGTACCACACTCGATTAGGAACATGTGCCGTCCATATATGTAGGGCAAAAAAGTCTCAGATCTCTGGTACCGACGGACGGCCTGACGCCCTTTGAGGTGCCGGTACGTGCCTCGAAATCAAGGGATTCCAACGCGTGATTTAAATGATCTTCACTTATGGAGTCGTAGGTGCTGTTAGGAGACCAGGAGAGGAGCAGGTACGGCAAACGATGCATTGATCGGAACCCGGAGTTAACGATGCCACTGGGTCGAGTTGATCGATACAAAGCGATTTAGCCCAAAGTCCGCTTTCGACATTGCAGTAGGATATTACTGTCGAGTCGTTGACGCGAAAATGGGCCGAACTGATACCGTACGCCCGAGATTCACCGCGTTGGTCGGGTTTGAGGTAGACGCACCGCCGATAATTCATGGTGCTGGGTCAGTTAGCAGAATCCTTTGTGATGTCTTAGTCCTATTAAAAGACTCGCACAACACGTACGGGTGAGTTGTCACGTTCGGGTGGGCGCTATTGGTTTGCGGACCAACGAATACGTCGGACGGTTTGAAGATGTTCTATCCTCCGAGTTTTGGGGACCCTACCTATACTTCTGCAGGGACGACGAGATGTGAGGTGGCCACAATCACGGTCGAGTTCGGGTTTATAACGAGGCCTTGCACGGGTACGATTACAATGAGCTCCACCTTGTATTCGATAGTGCATACGAGATCCGTACGATGTCAGAGGCGGGACCGCCCACGTCGATTGCTATCGCATTAGTAAAATCCTCCAGTTGGTAGTGGCCAACCAGGGCCAACTAGTTTCCAAGGATCCGGTCGTCCAGGGGAATTATTACTGTCCGACACGAACTACGAACCCTTCATACGGGGTCTAGGGCTTTGTTCAATGGACTGGCGGCCACCATACAGGGACTCCTAAAGTTATGCGCGCTCATGCTTAGTCGCCGTTCGGCGACATCAGGCGGTACGAAAGACGCAATCTGGGACGAATGGTCATAGGCTCAACGATACAATCCTGGGTTGATGCATTGCAAAAAATTAAAGCTCGAGCTGTTGATAAACAACTTTCGACAGAATCTCCCGGTCTTGTATGTATCTTTAGGATTCCATGTGCTGAGGACTCATGGACCTTAGAGCGTCTGTCAAGCCCGATCTGGCTCGTGGGGGCACAATTTACGGTTCTAAGCCTTGCCTTCATAGGTGTCCCTTCCAGGCCTCGTCCGTGCCCAATTTGTTGCGTATGGTGCGTAAGTTGACTCGGAACTTGAAGCAAGTTATTAATATCCCGGCCGAGGGCTCCCGCATTTACCAGGCACCTCGACCTCTAAGAACGTTTAAACACTCAACACCAGTTATCCGGCATTTACATCCGCCTAAGATTCGGCCCTAGTACTTTTTATACACAGTTATATCTCGAACGAGTAGCTTAGGAGAGGCACAGGATAACTAGATAATACTTAACAGCAGGCAGGTCCGCCTGAAGGGGTCGCAGATGAATTCAGAATAAGGCAAGGAGTATGAGCTAATTCGCCAAGAGGAGGAACTTTCGCATCAACTTTCCATGTTGGGAGCGTAAGAGACAAGGTGAGATGTAATGATGTCCTTGGTCAGCGCTCAACGAAGGGCACACGTTGGGCGGCACTCTATCAAAGTCCATGTAACGGCATTGGGTCCGAGTCGGTGTCAACGCTGGGTGCAGACGAGTTCGCAAAGGGGACACCAGGGTTTACGCTTACACAGCCGGAACTAGGTGCACTCATCCGGTGATATCAGGGACCTTTCAAATAAGAATAATCGGCCTGAACTAGAGGTTGGCGGTAATTAAGTTGCACGGAAGTTACGCCCGTGTATGGCTGGTCCTAAATCCGTTTCCTATGTCATTTTTTGCGAAGCTGTCGAGCATTCGGAGGGCCTGCGCCCGACTTAGCAGAGGCGTGTAGGCTAAGGTTTATTTTTGACGTGTACCTAATGATCTCAAATGGTGAAAAGACCATTAATACCGCAGTTCGTACTGGATGAATTAGGAGATGTCCTTACGACTTCAAACACTCGTGGTATTCTACTTCCCAACGGACGCTATCGAGCACAGCGAAACTTAAATTAGGTTAGATCCTCCTCAGCACGCCGGGGGACAGAGTGCGAGTATTAGGTCCACGAGCCAGCTCTTCAAACGACGGTGAGGTCGTTCCTATTACGCGAAATGAGACTAACCTGAGGCCGGACACCCACCTACTAATATATCGGAGTTATAACTTACTGCCCCCTATTTTATTTAAGTGTTAGCGAATCTAAGTCGTTTTTCTACCTTACCGGTGGGATTTGGCACTCGGCTAAACGGATTAACTCATAATCCTCGTCGGGCGACTTTACCGAGGGACCGCCAAGTCAGATTCGCCTAGTTTCAGCCGCTATTACACGACGCGGTGCCTGGCTGAGAAGTGCTAACCACGACTGCGCAAATCTCATAACTCCATATGACCTTGTGTGACATGCGTTTTCATCATCACGAACGCTTGTGATGCGCCTACTTGCAAGACGTCGTTTTTTCGTCCCCGCATCCAGCGTTTCGGTATGTTGCTGCGGCCCCCGTCCTATCCTTAACTAACCCGCAGCTGTGACACCAAGCAGCCGTAGTGGCCGGTTAGCGATGCCCTAACACCCCAATTTGACCAGTACACGAACAGCGGTCCGGCGACAGTATTAGTGCTAATCCAAACGTCGGACGGTATTATAAGTGAATCCATGGGCGACTTCTGTAGACTGTCCAGACGGTCGGCCGACGGTGTAACTACTTAGAAAAATTGCTCCTCATAGCGCTAGGAGCCCGGGGGGTCTGGGACTGACGCGCAAGAGGGTCGGCGATGCCGTGACATTTTTGGTCAAACTTCGACTCCGCGGTATTCCAGCACTTCTCTGCTCTCTATGTCGCTAATCGGGACACGGCTGCTTCGAACTATGCAGGATATTCGATATAAGTAATGGTCTTTACAGGGTCACGGGTCCTTGCGATTTTGTTGGAGATTAAATCCTGCGTCTTTTTCGTTCACGTGGGGATCCGTAAATCCGCAATCCAAAAGACTCGGAGCCACCTTGCCCGTATATCAATCGTCTGTCGCGATGACCGCAGTACCGAAACCCCGTGAGTCGGTTGCTTACGTTCCTTAAATCTGGTAAGTGCCGTGGGGGCCTGGCTAAGCCTCTCTCAGGTCTTGGAGCAACAGCCCGGGCCCCTTGGCAGATCACACCACCGGGTAACCTTGTAGTCTGGTTGCGTCTCTCGATGTTTTTATAACCCACTCGCTTGTCGCATCGTCAGAAGTTAACAGGTGGCGCGTCAACTAACATGTGCTGGTTATATGAGGTATCTCTCCATAGTGCTTTACCTAAACTTGCACGATCGACACGACCCTATGCTTGCAGCTGCACGCAGAGCCACACATACAAGAGTTTCCTGCAGAGTTTGATCAATACATGCTGTAGCAAAGTGGGTAAGCCTCAGCCCTTATCCGCACTTTGTGCCTACAATTACATATTGGTTTTAGCAGACCTGCGAACTACAATGCAAGATGATACCCAATACTAGTTTTATGATGGGACTCTCTGCCACCGCCCCTGCACAGGCCCAGCGCCAGCTTTATAATGTGTGATACGGAATGGGTCCTGAATCCCGACCACTTGCTGAGCTCTCTAACCAGGAGGTTTATCCATGCTCCGAATTCTAATTTGACCCCACGCAAAAAGAGAGGAATTATTTTTATATCGGTTCATCATAAACCATAGGCTCAGTATATTTCTTAGATCCGGATCAGGAGCTAAAACCGTACGAGTGGTAGAACAGATACTTCGTCCTGTGTTAGACCGCCTGTAACGTCCAAAGGACGAATCTTGCAATTGCACACAAAATTTGTAGACCGGCTAGTGGGTCACAATACATAGTCGCCAAGTACGGGCGTTTCTGCGAAGGAGCGCCCGTCGGCTTGTCCTAGAAACGGCTGCAATCATACCCGAATAGATAGAATATCTCACTACGAGCTTTCTTGGTTGATCACTCAATAACGGCGTTGGAGTCAGATCGTATCGACCCAACTTTCCCGGAGGTCGTCAAAGATATGCAGCTGATCATCGTCGGAACTAGGAGGTGAATCGCGAACGCGCGATTGTACTTTTTCGGATCACAACTATTAGTAAGGATGCCCATTCTGTCATACCTCAAGAAATCCCACTCAATGCACTTAATTAGGAATGGACTTACAGTATGGCCCAACTTGTTCATTAAAAGCAAACGGCCAGCCTTAACTTCGCGTCTCCCAAGGAGTTCTTCTGGGCTAAACCATAGGAAGAATGACAAACAGCTTGGTCAACCCACTTTACACGTTCGAATACGTTGCACCTTTGATCTGCACGGCAGTAGGTATTTGCTCAGCCATGATAAAAGTCTGGATAAAAGCAACGTATCAAACAGAATACCACCGTCGGGGCAATGTTCCTAATTAGAGGTCAGGTTAATTTGTGAGTCCAGGCCGTTGGGTATGTGCGCCCCCGGTCATAAACGGGCATCAGGAGACTGGAATTTGATCTGTGGTACCATGGAAGGAAG"
  //  val pattern = "TGGAAGGAAG"
  //  val d = 5
  //  val result = findApproxPattern(text, pattern, d).mkString(" ")
  //  println(s"findApproxPattern($text, $pattern, $d) = $result")

  //  val text = "CCTGCAACCATAGAGCAGAGATGAGGCCACTCAAAAGGGATAAGACCTACCTATGTTCGTTTTACGGGAAGCAGCGATATGCGTCCGGGTTTATAGTAACGTGGCCGCCAAAAGTTACGAAATGTAGCGGCTAAGTTCGACGGCACATCAGAGCTGGTTGGTGCCCTCATGGAATTTAGTCGCGTAGGTATTTGATTCTGAGAAAAATAGGACGTCTCTGACCATTATTTGACACTGAATGTTCTTGCGCTGTATTTTAATCACTTGTTCACCTCTTTGCTCCAATGCAGGAGTATAAGAGCTA"
  //  val pattern = "GAGCTA"
  //  val d = 3
  //  val result = countApproxPattern(text, pattern, d)
  //  println(s"countApproxPattern($text, $pattern, $d) = $result")

//  val text = "GCATGGGAATAATAATTCGCGGGGCATTCGCTCGCTCGCAATGGGTCGCCCAAGCATGGGGGGAATTCGCCCAAAATGCATGCATTCGCAATCCAAAATCCAATCGCGCATGGGGGGTCGCTCGCGGGCCAAGCATGCATGGGAATGGGGGGGCATGCATAATAATGCATAATAATCCAACCAAAATCCAAGGGCCAACCAAAATCCAAAATCCAAGGGTCGCCCAATCGCGGGGGGAATAATGGGGCATCCAACCAAGGGGCATAATGGGCCAAGCATGCATAATGCATGGGGGGGCATGCATTCGCCCAAAATAATCCAAGCATAAT"
//  val k = 9
//  val d = 2
  val text = "TTCAGGAGAGGCTACAACTTCAGGAGAGTTCAGGAGAGGATGAGATTGTTCAGGAGAGGATGAGATTGGCTACAACGATGAGATTGGATGAGATTGGATGAGATTGTTCAGGAGAGGCTACAACGAGGTCCATTACACTTAGCTACAACGCTACAACGAGGTCCATTTCAGGAGAGTTCAGGAGAGGCTACAACGCTACAACGAGGTCCATGCTACAACGCTACAACTTCAGGAGAGGAGGTCCATGATGAGATTGTTCAGGAGAGTACACTTAGAGGTCCATTACACTTAGATGAGATTGGATGAGATTGGAGGTCCATTTCAGGAGAGGAGGTCCATGAGGTCCATGCTACAACGATGAGATTGTTCAGGAGAGGAGGTCCATTACACTTAGAGGTCCATGAGGTCCATTACACTTAGAGGTCCATGCTACAACGCTACAACTACACTTAGATGAGATTGGAGGTCCATGATGAGATTGTACACTTATTCAGGAGAGGCTACAACTTCAGGAGAGGAGGTCCATGAGGTCCATTACACTTATTCAGGAGAGGCTACAACGCTACAACTACACTTAGATGAGATTGGCTACAACGATGAGATTGGAGGTCCATTTCAGGAGAGGCTACAACTTCAGGAGAGTACACTTAGCTACAACGCTACAACTTCAGGAGAGTACACTTAGCTACAACGATGAGATTGTACACTTAGAGGTCCATTTCAGGAGAGGAGGTCCATGATGAGATTGGATGAGATTGTTCAGGAGAGTACACTTAGAGGTCCATGAGGTCCATTACACTTAGATGAGATTGGAGGTCCATGCTACAACGAGGTCCATGAGGTCCATTTCAGGAGAGGAGGTCCATTTCAGGAGAGGAGGTCCATTACACTTATACACTTA"
  val k = 10
  val d = 3
  val result = mostFrequentApproxPatterns(text, k, d).mkString(" ")
  println(s"mostFrequentApproxPatterns($text, $k, $d) = $result")

//  val text = "GTCTAGGTGTCAGGTCGTCACCACCACCACCTCACAGCTGTCCACGTCGTCTCTAGAGAGGTGTCACCACAGGTCACCACGTCGTCAGCTCTCACCACCACCTCACCTCACCTAGAGAGGTCACAGGTCGTCCACGTCAGGTCGTCTCACCTGTCACAGCTGTCGTCTCACAGGTCAGGTCGTCGTCCACGTCAGCT"
//  val k = 10
//  val d = 2
//  val result = mostFrequentWithComplementApproxPatterns(text, k, d).mkString(" ")
//  println(s"mostFrequentWithComplementApproxPatterns($text, $k, $d) = $result")

//  val text = "GCTAGCT"
//  println(s"reverseComplement('$text') = " + reverseComplement(text))

//  val t1 = "TGACCCGTTATGCTCGAGTTCGGTCAGAGCGTCATTGCGAGTAGTCGTTTGCTTTCTCAAACTCC"
//  val t2 = "GAGCGATTAAGCGTGACAGCCCCAGGGAACCCACAAAACGTGATCGCAGTCCATCCGATCATACA"
//  println(s"hammingDistance($t1,$t2) = " + hammingDistance(t1,t2))

//  val text = "CATTCCAGTACTTCATGATGGCGTGAAGA"
//  println(s"minSkew($text) = " + minSkew(text))
//  println(s"maxSkew($text) = " + maxSkew(text))

//  val text = "CCGACAGGCTAGTCTATAATCCTGAGGCGTTACCCCAATACCGTTTACCGTGGGATTTGCTACTACAACTCCTGAGCGCTACATGTACGAAACCATGTTATGTAT"
//  val k = 4
//  val L = 30
//  val t = 3
//  val clumpedPatterns = superFastFindClumps(text, k, L, t)
//  println(s"Found ${clumpedPatterns.size} patterns:\n" + clumpedPatterns.mkString(" "))

//  val text = "CATGCCATTCGCATTGTCCCAGTGA"
//  val pattern = "CCC"
//  val d = 2
//  println(s"countApproxPattern($text, $pattern, $d) = " + countApproxPattern(text, pattern, d))

//  val pattern = "ACGT"
//  val d =  3
//  val result = neighbours(pattern, d)
//  println(s"#neighbours($pattern, $d) = ${result.size}")
}
