package specs

import breeze.linalg.DenseMatrix
import org.scalatest.Matchers._
import org.scalatest._
import weeks.Week3._
import weeks._

@DoNotDiscover
class Week3Spec extends FeatureSpec {
  feature("expectedNumberOfOccurences") {
    scenario("interactive quiz") {
      expectedNumberOfOccurences(9, 1000, 500) shouldBe (1.8921 +- 0.0001)
    }
  }

  feature("motifEnumeration") {
    scenario("example") {
      val dna = DNAMotif("ATTTGGC TGCCTTA CGGTATC GAAAATT")
      val k = 3
      val d = 1
      motifEnumeration(dna, k, d) shouldBe DNAMotif("GTT ATT ATA TTT GTT ATT TTT TTT GTT ATT TTT GTT GTT ATA TTT ATA ATA ATT").value.toSet
    }

    scenario("extra dataset") {
      val dna = DNAMotif("""
                TCTGAGCTTGCGTTATTTTTAGACC
                GTTTGACGGGAACCCGACGCCTATA
                TTTTAGATTTCCTCAGTCCACTATA
                CTTACAATTTCGTTATTTATCTAAT
                CAGTAGGAATAGCCACTTTGTTGTA
                AAATCCATTAAGGAAAGACGACCGT
                """)
      val k = 5
      val d = 2
      val expectedResult = DNAMotif("AAACT AAATC AACAC AACAT AACCT AACTA AACTC AACTG AACTT AAGAA AAGCT AAGGT AAGTC AATAC AATAT AATCC AATCT AATGC AATTC AATTG ACAAC ACACA ACACC ACACG ACACT ACAGA ACAGC ACATC ACATG ACCAT ACCCT ACCGT ACCTA ACCTC ACCTG ACCTT ACGAC ACGAG ACGAT ACGCT ACGGT ACGTC ACGTT ACTAA ACTAG ACTAT ACTCA ACTCC ACTCG ACTCT ACTGA ACTGC ACTGT ACTTA ACTTC ACTTT AGAAA AGAAC AGAAG AGAAT AGACA AGACT AGATA AGATC AGCAT AGCCA AGCGT AGCTA AGCTC AGCTG AGCTT AGGAT AGGTA AGGTC AGTAA AGTAC AGTAT AGTCC AGTCG AGTCT AGTGA AGTTG ATAAA ATAAC ATACA ATACC ATAGA ATATA ATATC ATATG ATATT ATCAG ATCCC ATCCG ATCCT ATCGA ATCGC ATCTA ATCTC ATCTG ATGAC ATGAT ATGCA ATGCC ATGGA ATGGC ATGTA ATGTC ATTAA ATTAC ATTAG ATTAT ATTCA ATTCC ATTCG ATTGA ATTGC ATTGG ATTGT ATTTA ATTTC ATTTG ATTTT CAAAG CAACC CAACT CAAGA CAAGC CAATA CAATT CACAC CACAG CACCT CACGT CACTA CACTT CAGAA CAGAC CAGAT CAGGT CAGTA CAGTC CATAA CATAC CATAG CATAT CATCC CATCT CATGA CATGT CATTA CATTG CATTT CCAAG CCATA CCATG CCATT CCCGT CCCTA CCCTT CCGAA CCGAC CCGAT CCGCT CCGGT CCGTA CCGTC CCGTG CCGTT CCTAC CCTAT CCTCA CCTCC CCTTA CCTTC CCTTG CCTTT CGAAA CGAAG CGACA CGACT CGAGT CGATA CGATG CGATT CGCAA CGCAT CGCCA CGCGA CGCTA CGCTC CGCTT CGGAC CGGAT CGGCA CGGTA CGGTC CGGTT CGTAA CGTAC CGTCA CGTCG CGTCT CGTTA CGTTT CTAAC CTAAG CTAAT CTACA CTACC CTACG CTACT CTAGA CTAGC CTAGG CTAGT CTATA CTATC CTATG CTATT CTCAT CTCCG CTCGT CTCTA CTCTT CTGAA CTGAG CTGCA CTGCC CTGTA CTGTT CTTAA CTTAC CTTAG CTTAT CTTCA CTTGA CTTTA CTTTC CTTTG CTTTT GAAAT GAACA GAACT GAAGT GAATG GAATT GACAC GACAT GACCA GACCT GACGT GACTT GAGAA GAGAT GAGCT GATAA GATAC GATAG GATAT GATCA GATCC GATCG GATCT GATGT GATTA GATTC GATTG GATTT GCAAT GCACT GCATC GCATT GCCAT GCCGT GCCTA GCCTT GCGAT GCGGT GCGTC GCGTT GCTAA GCTAC GCTAG GCTAT GCTGA GCTGT GCTTA GCTTT GGAAT GGACA GGATA GGATC GGATT GGCTA GGGAT GGTAC GGTAG GGTAT GGTCA GGTCG GGTTA GTAAA GTAAG GTACA GTACC GTACG GTAGA GTATA GTATC GTATG GTATT GTCAA GTCAG GTCCG GTCCT GTCGA GTCGC GTCGT GTCTA GTCTG GTGAA GTGAG GTGCA GTGCG GTTAA GTTAC GTTAG GTTAT GTTCA GTTCC GTTCG GTTGA GTTTA TAAAC TAAAG TAACA TAACC TAACT TAAGA TAAGC TAATA TAATC TACAC TACAG TACCC TACCG TACCT TACGA TACGC TACGT TACTA TACTC TACTG TAGAA TAGAC TAGAG TAGAT TAGCC TAGCG TAGGA TAGTC TATAA TATAC TATAT TATCA TATCC TATCG TATGA TATGC TATGG TATGT TATTA TATTG TCAAC TCAAT TCACC TCACG TCACT TCAGA TCATA TCATG TCCAA TCCAC TCCAG TCCAT TCCCA TCCCT TCCGA TCCGC TCCGT TCCTA TCCTG TCCTT TCGAA TCGAC TCGAT TCGCC TCGCT TCGGA TCGGC TCGGG TCGGT TCGTC TCTAC TCTAG TCTAT TCTCC TCTCT TCTGG TCTGT TCTTA TCTTT TGAAA TGAAC TGAAT TGACA TGACC TGACT TGAGA TGAGC TGAGT TGATA TGATC TGATG TGATT TGCAA TGCAC TGCAG TGCAT TGCCA TGCCG TGCCT TGCGA TGCGT TGCTT TGGAA TGGAT TGGTA TGTAA TGTAG TGTAT TGTCC TGTCG TGTGG TGTTA TTAAA TTAAC TTAAG TTAAT TTACA TTACC TTACG TTACT TTAGA TTAGC TTAGG TTAGT TTATA TTATC TTATG TTATT TTCAA TTCAC TTCAT TTCCA TTCCC TTCCT TTCGA TTCGG TTCGT TTCTA TTCTG TTGAA TTGAC TTGAG TTGAT TTGCA TTGCG TTGGA TTGGG TTGTG TTTAA TTTAC TTTAG TTTAT TTTCA TTTCC TTTCG TTTGA TTTGG TTTTA TTTTG").value.toSet
      motifEnumeration(dna, k, d) shouldBe expectedResult
    }

    scenario("interactive quiz") {
      val dna = DNAMotif("""
                GGGGGACACATGACAAGCGCAGGAA
                CAGAGGAGGCCAAATTGAGACTAAG
                TGAGAACGGAGTACTGGGGTCACAT
                TGAAAGAATCTTATTTTCAAAGGGG
                TGAAACCTAGATAACTCGACTTTGC
                CGTAGTGATAAGCTATGAAGCCGTC
                """)
      val k = 5
      val d = 1
      val result = motifEnumeration(dna, k, d)
      //info("Result " + result.mkString(" "))
      val expectedResult = DNAMotif("TGAAA TGATA TGAGA TGACA GAGAA").value.toSet
      result shouldBe expectedResult
    }
  }

  feature("count profile consensus score entropy") {
    val NFkBmotifs = dna"""
                     TCGGGGgTTTtt
                     cCGGtGAcTTaC
                     aCGGGGATTTtC
                     TtGGGGAcTTtt
                     aaGGGGAcTTCC
                     TtGGGGAcTTCC
                     TCGGGGATTcat
                     TCGGGGATTcCt
                     TaGGGGAacTaC
                     TCGGGtATaaCC
                     """
    val expectedResult: DenseMatrix[Double] = profile"""
                                              2 2  0  0 0 0 9 1 1 1 3 0
                                              1 6  0  0 0 0 0 4 1 2 4 6
                                              0 0 10 10 9 9 1 0 0 0 0 0
                                              7 2  0  0 1 1 0 5 8 7 3 4
                                              """

    scenario("count") {
      count(NFkBmotifs) shouldBe expectedResult
    }
    scenario("profile") {
      profile(NFkBmotifs) shouldBe (expectedResult :/ NFkBmotifs.size.toDouble)
    }
    scenario("consensus") {
      consensus(NFkBmotifs) shouldBe "TCGGGGATTTCC"
    }
    scenario("consensi quizz") {
      val p: Profile = profile"""
                       .4 .3 0 .1  0 .9
                       .2 .3 0 .4  0 .1
                       .1 .3 1 .1 .5  0
                       .3 .1 0 .4 .5  0
                       """
      val c = consensi(p)
      c shouldBe Set("ACGTTA", "ACGTGA", "AAGTTA", "AGGCGA", "AAGTGA", "ACGCGA", "AAGCTA", "AGGTTA", "AGGCTA", "ACGCTA", "AGGTGA", "AAGCGA")
      c & Set("AAGTGA", "AAGAGA", "ATGCTA", "TCGCGA", "AGGCTA", "ACGTTA") shouldBe Set("ACGTTA", "AAGTGA", "AGGCTA")
      c & Set("ACGTTA", "AGGTGA", "AAGAGA", "AGGTCA", "ACGCGA", "ATGCTA") shouldBe Set("ACGTTA", "ACGCGA", "AGGTGA")
    }
    scenario("score") {
      score(NFkBmotifs) shouldBe 30
    }
    scenario("entropy") {
      entropy(NFkBmotifs) shouldBe (9.91629 +- 0.00001)
    }
  }

  feature("medianString") {
    scenario("distance example") {
      val pattern = "AAA"
      val dna = dna"""
                TTACCTTAAC
                GATATCTGTC
                ACGGCGTTCG
                CCCTAAAGAG
                CGTCAGAGGT
                """
      distance(pattern, dna) shouldBe 5
    }
    scenario("distance dataset") {
      val pattern = "CTTAAC"
      val dna = dna"""
                GCAACTCTGCGGTCGGGCACTATTTCGCACAACCTTTCTTCCCCGCATCAGTGCCTACACGGTACTGGGACTAGGTTATCATGTAGGTTGTTTCAGAATAGGCTGGTAA
                ACCATATCAGCGTGGCATATAACTTTCGTGATACTTGCTAAGAATAGGGCAACGGGAAGCTTAGCCCGAATCGAATTGTAACTGGGGGCCGATCTCGCGTCACGACGCA
                AACCATCGTGTTGCTGAACACTAGGTCTGCACACGGCTATTCTTTTTCGACGGCAGTGGTACCAAGATTTCGCAAGATCTAGCCGCGCTATATTGCCACTTGCTGGCCC
                CTCCATGCAGATCGTGTATGAGGATTGCACCGGAGTCGATTCTGTTTCCTCAAGCGGGATCTTGTAGGCGCGTTATACGTCACACCTACACCATGCCGCGTCTTTTAAT
                TTTTAGGAATGTATTTGTGTCATCTTGATTATGTCTTTAATCGACTGAAATCGTGATTCACGAGGTTGCTTAAGTAATGGACATCCAGGTTTAAGAATCCTGTGTCTAA
                GATCCGCTACCTCGATTCACTACAAATCACGAATCTAATAACTTATGCCCAAGATAGTCCTGAGTCTGGGCTCCGCCTCAGTATATCTCGACCGTAGGGCACTTACCGC
                GGCTCTGCCGCCCTCATAGCCGATGATAACGCTTTCGCGGCATCACATCATCATGACGACGGAGGTCGAAAGAGGACATGTCGGCACCGAGACCTAAAAGATTTACGAC
                ACCATGCTTCTAGTGGATACTTCATCACTTTGCGGTCCTGCAGGGGTCGTGAGTTCTACCTGTTAGGGTTTTTCCTGACCTTATATACCAAACGTGACAGAAGCTGGGG
                TCCTCGACCGTAGACATAGATGCCCCAATATACTATAAGCCCTTTGGCTTATAGCGAGTTATGGCTTCACAATAGAAGCTCAGGAGTATCCGTCTCCCCGTCGGATGAA
                TATCGTAAACGTATAGCGCCAGAAATAACAGCTGCTTGCAATATGACAGGAATAAAAGGGGAAATTTCTGACAACATCTTTCTGGACGGACGAGCTACTCTGCGCGGAC
                CCTATTGCATTCTGCCGACTATGATATATTAGGTATTGGTTTAGATTCTGGTTAACCATGGAGGACCAACTGTAAAAAAACCAGATTGCATATCAATCATTGATCGGTC
                ACCCGTAGAGGCAACCCAATCATCTATGGCTCTACCGGGGGACAACACGGGTTAGCCCGGGTTTTTTATAACCAAACTAGGGCCCACTAAATCCCACTTACATATGACC
                GACCCCCTATAAGTCATCGGGCCAACGACCAACTTACGCATTGGTACGTAGGCCGGTGATGTACAGGTCGCGCAATAGCCACACATCGTAAGCTTTACTATGTGTGTTG
                GACTCAGTGGAGCGTTCGACGCTAAAATTTCGGGTCGAGTTGGGTGCCTGACGGTCGATATACATTTTACAAAACTCTGTAATGGAATGCCTGCAGCAGTTAATACTTC
                GCCTAGGGGTAACTCCCGACTCTTTGTAGCGCTCGGATAACGCGCTTCACGGGTCTGGGACTTCATATTGTGAGCTCAGCGGTGCTGTCTGTATACCGCCATAGCTTCA
                TCGGCTCTGCATTGCTCACCCGCATCTGAGTTGGTGCTGACGTTTCGCTCCCACACTGCAGCAATGGTTAGAGACATAGTGTGCTCAAAACACACTACCGCATGATGCT
                ATCACGGCTCCGTCTTCCCTCCACCTTGGCTTGTGGAAGTCGCCCTATGCTGACAAGACCCTGCCTAGTAGAAGAATCGGATGGCTCTGGGTGTCATTTGTAAGGCATG
                TGGAGGCCGTCCGATACTGACAAATCTCAGGATGCCTAGGCGGAGGCCTGCGGGCGGAATAAGTCTGACCGGCCTTAAGCTGTCCATACCTCTTGAACCTATCTTCATA
                ACGTAGGCCATACGGAGCCCAACGAGACCGTAAACCTGAATCATAATGCCGGCGGTGGGTGAGAATATTCCTACTCTAGCTCACTTATCGGACCCGCTTCGCACTTTAC
                GGGCGCTCACAAAGTTCGAGGTTATAAGGTAGGGTACAATCCGTAACATAACAGTCACATCCATCACCTTGCAAAAATACTGGAGGGGGACTACGGTACGAGTCTCACA
                CTAGGTGTTAGACGAAGGTGGGAGATTCTAAATAGCGCAACCCGATACGTTCGACCACAATCGACCACTCTCCAGCTACATGCTATTGTCAGCTGTGTAAGTGAGGGCC
                AAGAGAGCGGAACATCCAGGGTCCTTTGATTTCATCGAAACCCATACGTTGAATCTCCCCACCGCTTAAAGAACTATCGGTCCCATTCCGAGAAGCAACGGCGGTAGCC
                CAAATAGATGAAGATTGGTATTCGTAATTTTTAAGGCAAGCATTATGACGAGAGATTGCGTCCGACTGCTGCGCTGGTCTTTAACTGTCACGACGCGCGCTTTAGGACG
                TGGTTAAGACAATCAGCTCGTTGCGGATCCGGCAAATGTAAAGTTAGAGTTAGCGGTAAGACGCGAATTTTCGCAGCGATCGCGGTAGCACCCCCTTGCCCGGGTCTCG
                TTTTAAGGAATTACACCCGAGAGAAGACAAAAACCTGAAAGAGGGTAGTTTCATCGTCGATATTACAAGTTGCTAGCACAGATCCTACAGTATCAAACGTGGTCTCTAA
                TGTCACCATATCCGTCGTGCAGTCTGCGACGATGGTAACCTCCTCCTTTACTCTGCCCAGAACAGCAACGTTCACTCCTGAGCTATGGAAGTTTAACAGGTCCGATGTG
                AGTGTGTGACGCATAGTCTGACATCTCACTGCCGGCATTGACCGCCATGACGCTCACCACGAATTCGAGCGGGGATTTAAGGGTCCATAGAGCCGGGGTCTAATATATT
                CATATGGTGTCGCGGGGAGGCCCAGGAACCGCCAGCTTTGGACGTAATTGATGAAATATGTTATGAGGCTAGGGCTGTGTCATATTACCCAAATGTACATCGCGTTACC
                TATTCCTTAGTTCATCGCGCCTCGGGCAACCACTTAAGTGTCTCGCTGTCCACACTACTATCATACATAACTCCCACAAGGACGCCTGGGGTTTAAAGGTATGCTGTTT
                CACTCTCCTATGTATCGCTGAAAGCCTATAACAGTTATAAGGAAGACAACATCCAGAAGTCCTCTTAGGAGGTAATCGTTTTGAAGAACATTAAAGATACCGCCTCTTC
                CCCTTTCAACATAAGTCTCGTCCCGTTTCATGACAGAATTTTTACATCCACATACCTCGAAATCCCGGGAGGATCGTTGCCGAGATTCCCCAACATCGGGTCCAGTCGT
                GAAGGGTCTTAGTGCGGCAGCTCAAGCGTTCGTTATATGCAGGCGTGGTAAAACGCAAACGCAGTCGCCGATACACGCAACGTATGGGTCTTCTCGTGGTCAGATAGAA
                AAGACTGATATAAGCACCTCACAACCGGTCGCTGTCCCAATTTCATAGTAACAGCACGAGCTCTACTCGTCACTCCCTAACGAGCACGCACATGTGTAGCGAATCTCGG
                """
      distance(pattern, dna) shouldBe 50
    }
    scenario("bruteForceMedianString example") {
      val k = 3
      val dna = dna"""
                AAATTGACGCAT
                GACGACCACGTT
                CGTCAGCGCCTG
                GCTGAGCACCGG
                AGTACGGGACAG
                """
      bruteForceMedianString(dna, k) shouldBe Set("ACG")
    }
    scenario("bruteForceMedianString extra dataset") {
      val k = 6
      val dna = dna"""
                TGATGATAACGTGACGGGACTCAGCGGCGATGAAGGATGAGT
                CAGCGACAGACAATTTCAATAATATCCGCGGTAAGCGGCGTA
                TGCAGAGGTTGGTAACGCCGGCGACTCGGAGAGCTTTTCGCT
                TTTGTCATGAACTCAGATACCATAGAGCACCGGCGAGACTCA
                ACTGGGACTTCACATTAGGTTGAACCGCGAGCCAGGTGGGTG
                TTGCGGACGGGATACTCAATAACTAAGGTAGTTCAGCTGCGA
                TGGGAGGACACACATTTTCTTACCTCTTCCCAGCGAGATGGC
                GAAAAAACCTATAAAGTCCACTCTTTGCGGCGGCGAGCCATA
                CCACGTCCGTTACTCCGTCGCCGTCAGCGATAATGGGATGAG
                CCAAAGCTGCGAAATAACCATACTCTGCTCAGGAGCCCGATG
                """
      bruteForceMedianString(dna, k) shouldBe Set("CGGCGA")
    }
    scenario("bruteForceMedianString interactive quizz") {
      val k = 6
      val dna = dna"""
                CTTTTCCTGGTACTGTAACAACTGCTGCAAAGTCAATAGTAC
                GTCCAGCCGCACGGTCATATTGGACTACTGAGTCGATCTTAG
                CTTATTGAAAGCGCTATAAGTCTAGTTTTAAGCCTAATAGGA
                CATGTGATCAAACGCAGTAGTCCATTAAGACGTGCCTTCCCA
                AGTCAAAGCGCCTAAACAGGCCCCGGGTAAGCGCCTGTTTGT
                ACCGTTTACCTGTTAAGCGTTAGTTTGAGCCTCCGAAGTCTA
                CTAACAAGGCTTGCGCGGAGTCGACGGCCTACTAAGGAAAGC
                TAACCCTGCAGTCTATGCAGTCAAACGAGCAATGACTTTCAT
                TAGTGAAGTCAATGTCCAGACGAGCTTGACAAAGGCGGTAAA
                CACCGAAAGCTTGTTGTCTCTGTAACCGCCGCTCGGAGTCCA
                """
      bruteForceMedianString(dna, k) shouldBe Set("AGTCAA")
    }
    scenario("bruteForceMedianString quizz") {
      val k = 7
      val dna = dna"""
                CTCGATGAGTAGGAAAGTAGTTTCACTGGGCGAACCACCCCGGCGCTAATCCTAGTGCCC
                GCAATCCTACCCGAGGCCACATATCAGTAGGAACTAGAACCACCACGGGTGGCTAGTTTC
                GGTGTTGAACCACGGGGTTAGTTTCATCTATTGTAGGAATCGGCTTCAAATCCTACACAG
                """
      val m = bruteForceMedianString(dna, k, all = true)
      m shouldBe Set("AATCCTA", "GAACCAC", "GTAGGAA", "TAGTTTC")
      m & Set("CGTGTAA", "TAGTTTC", "ATAACGG", "AATCCTA", "TCTGAAG", "AACGCTG") shouldBe Set("TAGTTTC", "AATCCTA")
    }
  }

  def readProfile(profileString: String): Profile = {
    val a = profileString.stripMargin.split("\\s+").map(_.toDouble)
    new DenseMatrix(a.length / 4, 4, a).t
  }

  feature("probability") {
    val p = profile"""
            .2  .2   0   0   0   0  .9  .1  .1  .1  .3   0
            .1  .6   0   0   0   0   0  .4  .1  .2  .4  .6
             0   0   1   1  .9  .9  .1   0   0   0   0   0
            .7  .2   0   0  .1  .1   0  .5  .8  .7  .3  .4
            """

    scenario("example 1") {
      probability("ACGGGGATTACC", p) shouldBe (0.000839808 +- 0.000000001)
    }
    scenario("example 2") {
      probability("TCGGGGATTTCC", p) shouldBe (0.0205753 +- 0.0000001)
    }
    scenario("interactive quizz") {
      probability("TCGTGGATTTCC", p) shouldBe (0.0 +- 0.0000001)
    }
  }

  feature("profileMostProbableKmer") {
    scenario("sample") {
      val text = "ACCTGTTTATTGCCTAAGTTCCGAACAAACCCAATATAGCCCGAGGGCCT"
      val k = 5
      val profile = profile"""
                    0.2 0.2 0.3 0.2 0.3
                    0.4 0.3 0.1 0.5 0.1
                    0.3 0.3 0.5 0.2 0.4
                    0.1 0.2 0.1 0.1 0.2
                    """
      profileMostProbableKmer(text, k, profile) shouldBe "CCGAG"
    }
    scenario("extra dataset") {
      val text = "TGCCCGAGCTATCTTATGCGCATCGCATGCGGACCCTTCCCTAGGCTTGTCGCAAGCCATTATCCTGGGCGCTAGTTGCGCGAGTATTGTCAGACCTGATGACGCTGTAAGCTAGCGTGTTCAGCGGCGCGCAATGAGCGGTTTAGATCACAGAATCCTTTGGCGTATTCCTATCCGTTACATCACCTTCCTCACCCCTA"
      val k = 6
      val profile = profile"""
                    0.364 0.333 0.303 0.212 0.121 0.242
                    0.182 0.182 0.212 0.303 0.182 0.303
                    0.121 0.303 0.182 0.273 0.333 0.303
                    0.333 0.182 0.303 0.212 0.364 0.152
                    """
      profileMostProbableKmer(text, k, profile) shouldBe "TGTCGC"
    }
    scenario("interactive quizz") {
      val text = "CATGCCTCTTTCCATGCTTTCGATCTGGAAGACCATGCAGTAGCTGGACCCATCGGACCGCTCTGCGGGTTCACGCCAGGCCTTCGTAAGGGAAATGTTCACTACATATGACACCGCAAAGCACTCCGTTTCAACCGGCAATCACTTGACAGCGTAGGTATAAAGTCTGCGAAGAAATGATGGCGTTGGTCCCAAATAAGTTATCTTGCTATAACCCGGTCAGTCTTGCCGTTCCCGAACATATACCCGGAGTCCGGGGAGTACTCGGGTAAAGTCATAAACCGCTAAATGACCGCGATTAGGAATATTATCGTAGACAACGTCGCGTTCTCTTGAGTGACCAAGGCGTTTTGCACGTGGCTGGATCTTTATTTCTAATTTGAAACAAGGAAGGAGGAGCGCAGTCCGATCATACGGGCGCAACTTATGGGCAGAACTTACTTGGAACGAGAGCGCGCCTCTTCCGAACTGCCAGTCTCCCGACCCACTGACGAATAGTGCTTCAACGATAGGTGGAGACTTATTAGCATACTAGAAGCCAGTCTAATGGGTATCGCTCTAAAAAGGTCGTCATAACGCATAGCTCTCCCCCGCTCTTCAGGGATGAGGGGTAACCCGTTAACGTTCACAAGGTGAGTCTCGCCTTACTACCGATTGCGCAGTTGGCTCAGGCTCTTGTTACAATAGGACTACCGAGCTCCGTTACCAAGCGTCGCAATGATCCGCGCGTACTTCCTTCCCTCCCCGCTCCCCCTAATGGGCCGCGCGCGCCGACTGTGGGATGGAGTGGTGCATCCATTTAAGGCATCGACTGCGTCGAGCGCGCTCGTTGCAAATTGAGTTACCCCACTTCTCAACCCATGTATGGGTCAGCACACACTAGAGAGCGAAGACAAAACGAGGGTCTCGTATAACAGAAAAGGAGTCCAGCTAGAGCTTGCCTCGATTGGCGAGCGACGCAAAAACACTTGGACGGTAGATACCACGTGGTAATGAAAGG"
      val k = 13
      val profile = profile"""
                    0.25 0.316 0.237 0.224 0.224 0.263 0.25 0.316 0.224 0.211 0.197 0.184 0.303
                    0.171 0.224 0.211 0.289 0.316 0.329 0.25 0.211 0.289 0.263 0.224 0.276 0.237
                    0.289 0.171 0.303 0.316 0.263 0.132 0.25 0.276 0.329 0.276 0.197 0.197 0.276
                    0.289 0.289 0.25 0.171 0.197 0.276 0.25 0.197 0.158 0.25 0.382 0.342 0.184
                    """
      profileMostProbableKmer(text, k, profile) shouldBe "TTGGCTCAGGCTC"
    }
  }

  feature("greedyMotifSearch") {
    scenario("sample") {
      val dna = dna"""
                GGCGTTCAGGCA
                AAGAATCAGTCA
                CAAGGAGTTCGC
                CACGTCAATCAC
                CAATAATATTCG
                """
      val k = 3
      val t = dna.length
      greedyMotifSearch(dna, k, t) shouldBe IndexedSeq("CAG", "CAG", "CAA", "CAA", "CAA")
    }
    scenario("extra dataset") {
      val dna = dna"""
                GATGGACCGGGCCATACATGGTGACACGCATCAGAAAGCTGTCCCCGTGCCTTATGCGCTGTCTGTTAGTACATCTCTCTCAATGGCCGTATTTTCAGAACAAGTATCACTTGGATCATCATCTACTCGACGGAGGGCGCGCAAGTGGGTATCTCG
                TAAAAAGGTATAAGGGAGTCATATCCGCAGTCCTAGTGACCTTTCCCGGCCCTAGCAGTGCTCCGATAGCCCATGGATGAGACGTAACTCGGCTACTGTTTGTGACTCAAGATAGTTGCCGTCGATATCTCGGATTCTGCTTATCGTGTTACGAGC
                AACCACGAGTACCTCTGTCGTGGTCCTTCACCAGGACTCGAAATTTGGCTCACGCCCAACGCCAAGATTACGTCGATCGTTCCTGTTGATATCTCGCCGCATATCAGGTTTATACTGATCGGCTCAGTGATTGTTAATCATCGGCGCGGGTTGTCA
                TGTCATGTGCGGATACAGTGGTGACACCAGGTCACCTCCGACCTAAAAGCGTTCAAGGTATGGCCCGAAGAGGTAGGTATCTCTTGTGCCCGCTGCTGCTATCACTCCCTGTGAGCCCCGACACGAATGTTAAACCAGTTTATATTCGCTCGTCAT
                AACCTAAACCCTTGCTTCCCACCATCCCTGCGAAGCAACCTTATCCGTAGTTCAGTCGCGCTGAACTCGGAAAGTGCGCTCACGAGATTCTAACTTACACTTGTTTAAGTACCACGTCCGGTGGATATCGCTGGCGTTGAAGGATAGTTCTGGTTA
                GTGCCCGATATGCCCGTCAGGGTTGAAGTCTGGGAAGTCGTTATCCCAAACGAAATACCCCGTTCGCAGGCGTGATGTATATCCTGATTAGTACCGCGTATAATATTAGTTTCGCACAGGAGCGTGCTTGTTTTGGGTCATGGATTGGGTACAGCA
                TAGTCTTCGAGGCATCTACCTGCGACCGAGCTTGCGATCCAAAAGCATACCCATGAAGTTTGCAAATCTTTCTTAGAGCTACAGGTAGATATCCCTGGGCCGGTAACTAGTAATATGTACAGTTTAGTTGTCCTGTACAATACTGATTGGAGTCAG
                AGGAGACGTGTTTGGTAGGCGCTCGACCCTTACCCCCCTATCTCGACTGGCATTGGACGTCCTCAGACTGGTGGATTTGACCTAGTGGTTATCACGCACATGGGAGAACCCGGTCAGAATACATCCTGTTACAGTCAGACGCCGGGTCATTCGCAA
                TGTGGGGATCGTCTGATTCATCGACGTCATGGAAACGGGGACGGGCCAGTGGTTATCCCATGCTGCCTTTTAGGAATTCTAGGAGGCGTTCCTAAATAGCTCGCCCGACGATATCCTACTTGATTGTGGCGGTATACCTTGCTGAACCTCGCAGTA
                CGCAGTGCACTAGTGGCTATCGCCTTTCTATCCCTGAGGCGTTTGCGTTATAAGATCACTCTGTCGGTGTGAAACCACTGAGTCACACTGACCGGTCGACTGGCCCGTCATATGCAAGTTGAAACGCTTACTGCCGGGTATCGCTCTAAGCTCGAC
                TACTCGTAACTTCAAAATCTCGTAGGGTCTGCAGAGTAAGAATCCCGGATACTTCAACATTATCGATTCGTCAAGACGTGCGGAGTGGATATCCCTTATTCCTATACGTCACAAGCCGCGGTCAAGTCGCTTACGCACGGTAGAGCGGGAAACCCT
                GCTCTAGTACGCCACAGTGCCAGTACATGACCTCACGAGCCGCCACTTACGTTGATATGTTATAAATCACTAGTTTCGTTGGTACAAACAATAAGTGAGAAGCAATGAGCAACTTATCTCATAAAAAGTGTGGTCGTTATCACACATGACATAAAC
                GAGACGGTCGTAGAAATTTGCGCTTGCTCGTATCTCAGTATCCTTCAAAGATTGAACCGGATCGCGGCGGCTAATATTGAAATCCTTAGACTTAACGTTGGTATCACTTTAGAATTTCTGACTTGAGGGTAGTGACTAGACAATCATGATGGAAGA
                GATCGGTGGCAGTTGAATTAAGACTAGTTATCCCCTGCTTACACTTTTTCCGCCCGGACACGTGTGACGGTAGTTGATATCTCTCAAGTATCCCGACTTCACGTACGATGCCACCCATCTCCGGCAAACACACTTCTATAATATCGTGGAGCCGAA
                GTAGGTATCACCAGAGTTCTCTCGGTATGTGGCGCTAAAACCTCTTAGAGTATGAAGGGTGAAGACCAAGCTCATACCACCCCTATATAGGGCTAATTAATTCCACATCCAGGCAAGATGTCACCCTACAGGTCGCTCACTTGTGGAGAACATCAC
                GTGGCTATCGCTGTGATCCGTCACACAAAATCAACTTTGTAGTATTTTGGGTAGTCGGGATAACGCGTGGTCTAAGGTGAGCTGCCTTTGATCCGTTGGGTGGCTACCTTGCAAGTTACCGGCTTGTCACTAGATATAACCGGAAGTCTCTGCAAA
                TGAGCAGACCCGACAAAGGCCATGACTTCAAAACCGGTTGTGCAGCGACAGGTACTTTAAGTACGGCACCATTAATATCGCTATACTTACGAGTTAGTGGGTATCTCATGCAAACAAACTGCTACTAGGAACTTAGACGAACTTACCAGGAGGATT
                AGTGATCTGAGCATAGTATACTGAGAACGTGTGTGTGACCCCTCCAGCGTCCCCGGCTACTGTTCCAGATCCTAACTAATTACTGCTAGCGATCTGGTCGATATCGCTACGGAACGAAGCCGTACAATCGCCCAGAAGCGGTTAGTCAAGGGCGTT
                CAAAATGGGAGTACTTCTCGTAGAATAATTCGTCTGTAATTCCTAGGTTCCATAGATAGGCCTCGATAGTGAAATTCCTTCATGCCCCGAGGTGGCGTTGATATCTCCTTTCTAAGCGGTACCCTTAAGAGTACTCGCGATGGGCTTATCCTCCTC
                GTTGGTATCACCCCCAATCCTCTTAGTTTACACTGTAAGATTAACGTCAGGGTGTTGTGGATGGCTTTTCTAATTTAGGTCCTCGGGATGCTCAGGTGTTACTATCGGACTGAGTGAATGTAAGTCCGGGTATCAGCCATGAAACCACTGGAGATC
                CCTCGGAAAACGTCGTAAGTGGTATCACAATCCACTAGTCACGGAGGGCGGTGAGTGTCTCGATGCTCAACCCCCAACCCTCAGATGAGGCTATCTGTAGGTATCACTTACGTCACTACGGGGAACAGCTCGCCTTAAGTGTAGGCTAGGTATATG
                GGCGGCTCCATCCGATGTGACGGATTTCATGAGGCACAAGCGCTTCACTCCCTATTTGGCTCGTGACAAAGTTCAACGGCTTTGCAGATATCCATGGTCGTTATCCCGGTGGTGAACCTACCGTCAAGTCTCTACAGTGCGCGAAGTGTCCCGGGC
                TACTAGTATAAGTTCCGAGCCAAATGGATGGCCCAGGCGCACTAGTGTTAGAAGGATTCGGGCTGTAGGTACATCAAGCTCGAATTTGTCCCACGTCATTCTGGGCCACCCGGACCACAGAAGACCTCTCTCTGTGCCGACGGTGTGGTTATCACG
                GTGGTTATCACCGGGATCGAATACAGATACGTCTGGTACATGCCTTGTCATTATTCATACGCCCCCTGGGCCAACAATCCTTTGTCAACCGCGGTCAAAAAGGTAACTAGGATCGGCTTGATCTCTAATTCCGGACTGTTCACCACGGGTCGACCG
                CATCACGCAATGCGAACGACTGAAGAAGGCAAGGACAGTTACGCAACCTATCATGCGTAGATCAAGGTAATCGGGACCGGTCTGGAATTTAGGAGTGTTGTTATCGCAACCTGCGATCATAACATCCTCTTATTGCCTATAAACCGACCCTGACCG
                """
      val k = 12
      val t = dna.length
      val expectedResult = dna"""
                           AGTGGGTATCTC
                           TAAAAAGGTATA
                           AACCACGAGTAC
                           TGTCATGTGCGG
                           AACCTAAACCCT
                           AGTCGTTATCCC
                           AGTAATATGTAC
                           AGTGGTTATCAC
                           AGTGGTTATCCC
                           AGTGGCTATCGC
                           AGTGGATATCCC
                           AGTGAGAAGCAA
                           AGTGACTAGACA
                           TAAGACTAGTTA
                           TATGAAGGGTGA
                           AGTCGGGATAAC
                           AGTGGGTATCTC
                           AGCGGTTAGTCA
                           AGTGAAATTCCT
                           TGTGGATGGCTT
                           TGTAGGTATCAC
                           TGCAGATATCCA
                           TGTGGTTATCAC
                           TGTCATTATTCA
                           TGCGTAGATCAA
                           """
      greedyMotifSearch(dna, k, t) shouldBe expectedResult
    }
    scenario("interactive quizz") {
      val dna = dna"""
                AGGCCCCAAGCAGCGGCATATCACTCAGAAATAAGCATACCTCTTCGGTTACTGCAACCGCACCGGGCTGGGCTGCCAGCGTAAACTCCTTGCAATAATGGCGATACAGCTGCTGAACGAAACTTCGGGGGCTGTTTGTCTGGACCCAGCTGAAGT
                CCCTAACACGTTTATCCATGATTAGGAGCCAACGGCTCTGGGATTCACTGCTTGTGCTACTTTCTCCCGCCGCTAGGAGTACGGTGCTTTTGAAGGTGCCCCCCTAACACGCCGAGTCTAACTCCCGCCAGGCGCCGACAGTAATGGTGTCAGGGG
                AACGTGTGGAGGCGTCGGCGGGGCCTACGGGGCGCCGATTTCGGGTGACGACTAACATATACTCGACACGCTCTATTCTTAGAACTTCCGATGCAATCTAAACCTTAGTACTTCATTGCGAAACCCTGGGGTTTCTCGGCGAGCTTTCTTCATCCG
                CCTAAGCCCTAGTTAACATATAGCCGGATCTGGTGCATGAGACGTACCCGATGCACTGAATTTTCCACAACTTTCCTGCATCCGGTGCTCTCGGCGAGGCAGATAGTGGCACGCCACGCTGAAGCGGGTTGCCAGAACAAGTAATAAAGTAATGTG
                ATCGACCCCCAAAACCACATTACTTTCCTGCTGCCGACCCTGGTCGAGCCCGAACTAGCTGCTTATCGTATCCCACGCCTCCTATCTCATGCTTCTCACTTATCATAACCCTCATGAGCGGGCACCTGCTCCTCGACCCTTTCACAGAGATACATC
                CAGGAACGTACGATCTTCGGCATCCATTGTTTGCAGGATAAAACAATTGCTGAGCAATTATCGATAACGACCTTCCATCATCCCAGCAACCTGGCAGTGGGAGATCATTCTGTGCGTGCCTCACCCCGGCGTTTACTGCTTCCGCGTACGGCTAAT
                AATCTATAAGAAACAACGGGTCCCTGTGGTAGTGGTCATGCGCTGTCTTTACTGCCTCCGAAGCCCGCGATCCAGTGGCGGCGTATCAGCATGGCTCAATGAGGCATCGTACCGGCGTAAGTGCGGTTGGAACGGATAATGGGGTTCATTCCTTTC
                TAAGGTACTCCTATAGAAATACTTCCAAAGGCCTTCCCACATCCCCGTAGATTCAGAGTCTACAGACAAAACAATGGCCAAGGAAGTCAGCCACTCAGCCGCTCCGTATCGGCTAGAGGCTTCCTACATCCGCATGGAGTAACGGAGCCGTTTGAA
                GCAAAGCACTATTTCCTGCCTCCGAGATTGTTACTATATCGAACAGACACGTTTGTCAGCGAATATGGGTCATTCGCTTCCCAACTGATAGATCTGGGCCGGACTCGTATCGCGGGGCTTCTGGGTGATCATGCTGCCCTACCAGCTTAGGACTTT
                GGATGGGTAACTGTTGGTTTCAATGGTGACACGCAAATGCCGAATGTGAACTCATAATAATTGCTCCGTCCGTTCCGAGCAGATTACGGGTACCCAGCACTTAAATCCTACTACGTTGTGTTTCCAGCGCTTACTCCACCCGGAAGGTTGCGGAGA
                GCTCGATTTAAGTCAAGCGGTTAAACCCGCGTTTCACATCTTACGGACTTACTACCGCCGCTCCGCCTGTGAATTGTTCCATAGGTGCGTGCCGCCACTGTTCCAGGTCAGCCTCTTATGGAACCATTTATTCTCCCTTTATTGCCTTGCTGAGGT
                GCCCCAAACCTGGGGCAATGGATATCGCAGAGCAATAGCTTGGTCAAAACCCGCCGGAGGGTTGGCTATAAGTGCCATGAGCAATTCCGGCAATGAAGGTCCGGGACGAGACTGATAGTATTTCTGCCCCCGGAAACAATAGTAGTCTCTAGCCGG
                TACATTGGATCGCTAGATGCATAAATACCCGTACAGCACATGTGACTCTTTCTACACCCGCTCCCGTGATGAACCATTTACGTAAGGTATCAAGATGGGGCCCGGTCCGAAGGTTTGCCCCCTGTGGTGAGGCGACCTAGAATGCTATCCTAATTG
                CGCAGTAGATAAATAAGCGGCTCCGGATGCACAAGAAGGTTGTTGACTATAGGCCGAAGACGTGAGATTAATGACACAGGTTGTTTCCTGCGGCCGTATCCAATACCTATACGTCGGGGAGTCTCGGCAAGAAGAATAGCCGCGATGAATTACTGT
                AGGTGACAACCGGACCTGATATGATGCTCATATGAGACCGACTACTTGTTCCTGCTGCCGTGTGGGGTCTTTGAGCCTGGTTAGGGGTCGGTCCTTCGGCGGGCTGGAGGTTGTAGACAAGAACAGTGGTCGCACGCCTGTTACTTGCCCGAGCAG
                TGGATTGCTGTCAAGTAGTTAAAATAATAACAGGGGCCCTCCAGCCGAGGCACCACCTGATTCCTTCTCCCGCTTTAGATCCTTTGGCATGAGTCTAAATGCCTGCGCCCCTTAAACGACGAGATAACCTCTGGCCGGTGAACTCGTGAAGGGATA
                CCCCGTCCCCGTTAGGAGATATGAGATATCGACTCGACCCAACCGAGTGCAGCACTAAACTTCCTACATCCGTTTTGAGTATCTCTACAGCCAAAAAGGGTCGTAGAACCGTGATTGGACCGTTATCCAGTCAGAGACTCGTCCAGGGAACCCACT
                TTGCTTCATCCGTGGAAAACCCACGCTTTCGAAAAAGGAGCTTTCCAGCGTGTCTATAGGCCCAGATCCCATAGATCCCTTCCCCCTGCGATAAGTACTATATCAACAGCCCTGAGTACGAGTGGCCATAGGACGGGGTTGTCCGTTAATGCTTAA
                AACAGACTGCTTATTTATCATTCCGCGATATTACATTAACTTACTGCTGCCCCCTACAATCCTAAACAGAATTTATGACGGCTTGACGGGATGACGTGATGGATCTATCTGATCTAAGTTAGGCGCATCACGCGCTCACAAAATTTGCTTCTCCCG
                CCGGCCGCCCCGTTCTTTCGTCATGGGTCTAGCACGGCTCTTAAAGAAGTATAGCTGGAGCACCAGAATACATTAAATCGTAACCTATTCGAAGAGGGCTACAATGGGCTACGCAGTGACGCGTGCGGGTGATTTCTGCGGCCGCAGCGGCTTTGC
                ATGGTTATTCAAACATAACTCACGTCGAAACTAATCCGGTATATTTTCGATCGTAGTTCTGGGAAGTCGATTTATCCAGCCGGGTACCCGCAAGTGGAGCACCTAAAACATTGATCAAAATTGCTTCTCCCGCAGCCCGGGTGGGAGCGAAATAAC
                GTGTTTAAAATTACTTAAAGTCAGGTTTGCAAGTGATTGAGATCCAAAACATACCTGGAATATATGAAAAGCTTGCCCTCCGTCACCTACGCGGGAAAGCTTTAGCAGCGTGCTCGAAATTTCCTCCCTCCGAACGATCACTCAGTACTTTCCAAT
                GGGGAGACCTCATTACTCCCGCCGTACGCGGCACTGAATCCAGCAAGTTGGGAAAGGTTTCGAGCACCGAATGTCGCTGCCGCCTGTAATTCCATATATGTTCTTTATCTGTCCGGCGGCAGAATCTCATTTCGAGCCTACGTTATACCATTTGGC
                AAGTGATTCCATGGAGTAGTTACCTCAGCGCACGATGTGTGATTGTGGACCACATAGCGTCCCGCGTCCCTGGTGGAATCCCAGGCGCTGTGGGCGGTATGGTCTAACAGCCAGCTAATCCTCTTCCTGCTTCATCCGGTAGTGTTACTCCAACCG
                AATCTCTTGTTCCATGGCTGTCCTAACGCTATCAGGGCACTCTAGACATAAAGGTCTCAATTACTCCCCCCGTTCTCTGGAGGAAAAACTCAGTTCCCTGCCCGTGCCGGGCCATGGAGGGGGCATATCAGGCGCCCCTCAAGGTCAAATATGTTG
                """
      val k = 12
      val t = dna.length
      val result = greedyMotifSearch(dna, k, t)
      val expectedResult = dna"CCGCACCGGGCT CCCTAACACGTT AACGTGTGGAGG CCTAAGCCCTAG ATCGACCCCCAA ATTCTGTGCGTG CCGAAGCCCGCG ACGGAGCCGTTT CCGGACTCGTAT CTCCACCCGGAA CCGCTCCGCCTG GCCCCAAACCTG CCGCTCCCGTGA CCGAAGACGTGA CTGCTGCCGTGT CTCCAGCCGAGG CCCGTCCCCGTT CCCTTCCCCCTG CTGCTGCCCCCT CCGCAGCGGCTT CCGCAGCCCGGG CACCTACGCGGG CCGCCGTACGCG CCTCAGCGCACG ACTCCCCCCGTT"
      //println(result.mkString(" "))
      result shouldBe expectedResult
    }
  }
  feature("greedyMotifSearchWithPseudoCounts") {
    scenario("sample") {
      val dna = dna"""
                GGCGTTCAGGCA
                AAGAATCAGTCA
                CAAGGAGTTCGC
                CACGTCAATCAC
                CAATAATATTCG
                """
      val k = 3
      val t = dna.length
      greedyMotifSearchWithPseudocounts(dna, k, t) shouldBe IndexedSeq("TTC", "ATC", "TTC", "ATC", "TTC")
    }
    scenario("extra dataset") {
      val dna = dna"""
                ACGAGAACTGTAATGGAGACCAATCGGGTCGTATGTACGACACGGATCTTCTGTATCGATCATCGCTTAACTTATACGATCTCATTCTCACGACGATCCTCAACCCCGGATACCCGCACTGCCTCAATCCGAAGTACTGCGTAGTACTTTACCCTT
                ACCTGTGATCACTCAGAGAACAGAGGATCCGGGTTGGATGTCAGTGTTATGCCAAGAAACGAGACCTAAGGTGCCGTCCCCGGCGGAATGCTTCTCGCTTCCCCTTCTAAAGGGTCCTGGCAAAATGCTTGTGACTTTGAATGCCCTCACTGAACT
                AAATGTGAAACCTATATCAGTCATTATACCGGCGCGATGTTAACTCGCACCTGATTGCAAGGTCACTGATCGCGTCACTACACTAGAGTTTATTCATACCTGCATGGGGGGCATGATGGATGAATTTTAACTAGGTGATCGTGACCAATGTTCACC
                TTTAACCGAATGAGAAGGGTTTCGTTTTAGGCCGTCGATCCGCCGCTTCTTCTCTCGACTGAATCGGAGGTTTTAATGTGTGTGCTAAAGTGAACTGCCTAATAACCCGCTAGGGGGATGATTTATTGTATCTGCAATGTACGGTGGTACATCCCG
                GCTTTCCCGTGTTCTTCGTGCGCTCGGGACCAGAGATCAGAACTAGTGCTAAAGCCATGGAAGCATTTAGCCGGCCGATGTAGTAAAGTTGCCCATATTTCTCCCTAAACCAGCGTATACGTCGAAAACTTTCTTCACTCCACTATGTATAGATGG
                CGCTTAGCGCATCCTCGCTAAACTAATTTGTAGGAGCAATCGCATGTCGACACCGAGGAAGACAACAAGTACATTAGTTACACGCTTCTTACTGGGGATAAAAATCTAGGATCGCGTGATCGGCGTGCTCCGGCGTCAGGTGACTTGATGGCCCCA
                AGTCATGACAATTCGCACGAGGTGACTTTCAATCGACTTACGTACTGCGCGTCGATGTCGCTTCACTCCACTAATACCCATATTCCTAACACGCCAGTACGGTTCAGAGTCGGCGGCTGAGGGGCCCTAGAAACGAGACACCCTAGAGGCTCTGGG
                ATAATAAACGAGATTTAGTGCTCCAGGTCCCTCTAACTTCGCTAGACTGTTCACGGTACTTAGAGTAGCTCAGAAATCGCCTGTCTTCGGGTTGGTTTTTTCAGGAGGTGCTCTGTGCGTTAACATACCAAGCCATAGCTGCTTTTCCTCTACAAA
                CCTACCGGAGGACTTCACTGAACTAAGTACTGGGGTGCTAAGGTCGAACGAGATGACTGGACCCTACTCTCTACGGGACCGACGCCCCAGGGCTTAATTCATATTGACTAGATTTATGATAATAATAGACTCGGCGGTTTGTAGCTTTCCCCTGAA
                CCGTTACTCCGCCGCTGCTGATCCTACTCCACGTGGGGCCCCCCAATATGCACATCTTATCGTCCCTGGACTGGCAGTTGATGCGAAATAATATTCGTGGGTATGATAACGCGCTATACTGATAGAACCACGGGGACTCCTGTATTCGTCTCGCCA
                ATTCGTGGGTTGAAGCCTTTAAACGGGATGGCCAAGTTGATTGGGTCTAATTGATATTAATTCTGGTGTACTGTACGAGACCGGTGCAGCACGGACGGGCGGTTTCAACAATACTCGTGCGCCTGGAGGGTACCTCGCTGAACTCGCATATCAGGT
                TGGTTACCCTCTCTTCACTTAACTCTTGTATCAAGACGTTTCTGTGAGACAAAGCAATGGCCGGACTTTGGGGCGCGTGCTCTGGAGATCCAAGCACTCGAGGTCAGCGGTATAATATAACGCATCCAACATGCAGACTGTGCGTGGGGGCCCAAA
                CCTTAGCGGTGTCGGCCATCATTTATCGAGCTGGAACTCCGGTGGGTAACGTGGATCCGCAGCAGGCCTTACCGTCACTTAACTTGTTACTAGAACATACGTGGAACCTATGCATGATCGAGATAGAGTGCGCTCCGCGGTACACCGCGCTCTATA
                AGTTACAACACGACAGGAACTATTTGCTAGGCGTTACATCTCTTTACTTTTAGCCCCTGGATTTTGAACGCATGTCAACACGTTCCACCATGGGTATAAGAATGCATGGACAGGGTTAATGAATGTGTCTCGGTCCGTTAGCTGTTACAATATACC
                CTTAGCAGCCCACGTCGCTGGACTGTGTTATATTACGAGGTCGAATAGTGAGGTTAACAGTCTCCGTTGTAACTTAATCCCGATATCACGCAGTGTATATGGTCGCTGTAGCTTTCTGGGCAGCTCGCACACCGCCAATTCGCAGAGGCGACCAGA
                TGGTAATAGGCTTCGAAATAACTCTTGGATTGCAACGAAGGTCCGAGCCTTCTCTGCACTTGGATACATTTTGGACATATGAAAGGATGGGTGCTCGGGATGGGACTTTGGTTGCCTGCAAGACGGCGAGACCACCTTACTGAAACCAACATCTTA
                TTACCGGTAATCTCTGATCGCCCATGCCGTCAGGTGCCTTAATTTAAGCGAGAGCTAAATAGAAAGCTGCGCGGTTTTAGCAAAATGAAGTATCAGGAATAACATGGGTTAATGTCACAAACCTGAGGGTTACCTCTCTGCACTCCAGGTCCAGCA
                AATTCAGCTGGTCAGTCACCACAACGTCTCTAGACTCGCACACCCAACTATTATATCACGTACAAGCCGCCCCACAACCGGCATGATAATGTCTGCACGGCCCAACTAACACGCCAGATGACGTACTTTTCGCGGCAGAGCAGTATTCGAACTCAA
                CGTACCCGTTATACAAGCACCATCTACAAAACGTTAGGTGTCAACGATCGTGGGCCGGACTTAGGGGTGAGACCTTAAAGCACACATTCCCTCCCACATCACTTCACTTGTCAAAAATAAAGTCGAATGATGACTACCTCAATTCCTCGCGAAAGC
                GCTGACACGTATTACGAACCGAGACCAGGCGCGACCCCAACCTGGACTAACAGCTATCCCTTTGTTACTTGGCACGTACGGTCAAATCCCGGTGGAGTTATTTACCGAGGGTGCGCCATGCATCGCTCAACTCCTAATGGTCGCCTGTACTTGGTC
                CGGCCTTGGTCCAATTCATCGTAACATTCTGTGAATCTACGGGTACTACTCGACCACGCTTGCTTCGCTGAGCTGTACCGCAAAATCGAATGGACCCAATAATCTGAATCCTTCGGTATACATCACTAGACTCACGATTCAGTATGCCCTCAATCA
                ATCCGAAACATTCAGTTCCGATGGCAACGACGACCACCCAGCACGCATCATCACTCGACTGACCCTGCTCGAATACAGGCGTATCTAACAACCAGCGGATCCAGGGCCCATGCTGAGGCTATTGTCACTCCCGCCCACCCTGTATGTATTCGGATT
                CCCGGATCGCCCGGTCAAGCACTCCAGGGCTTCAGCGCTGTGTACCTCTCTGCACACTCCGGTGGTGGGCCCCGTCCCTACACTGCGTATTCAAGTGATAGCTCGTACGATCCGCATCGAAGGCTGACTGCCCCTCTACAACAGTGCGCTCGCACT
                CCCGTATGTAGGTGATTAGACCCACCAAGCAATCCGCATGTTGCGTCACCGTAGATATATGCAGCGGTCATTCTTCGCTTGACTCTCTGACTTGCCCATTTAGAAACTATCCACTTAATTCCCCTTGGACTTGGGGCCTGTTTTCGGTCGCTTTGT
                CATTTCTATAAAGCTACAATAATAATCCGCGCTGTCGGCAGACGTGGTACCGACCCTACTCCTACCGTTTGAGAGATGGAGGGTCTTCCCTGAACTAACGGCATGCATGAGAGGGGTACGACCCTGGTACTTCTGAAACCAGCATCCGCGGCGACG
                """
      val k = 12
      val t = dna.length
      val expectedResult = dna"""
                           CATCGCTTAACT
                           CCTCACTGAACT
                           CGTCACTACACT
                           CTTCTCTCGACT
                           CTTCACTCCACT
                           CCTCGCTAAACT
                           CTTCACTCCACT
                           CTTCGCTAGACT
                           CTTCACTGAACT
                           CGTCCCTGGACT
                           CCTCGCTGAACT
                           CTTCACTTAACT
                           CGTCACTTAACT
                           CATCTCTTTACT
                           CGTCGCTGGACT
                           CTTCTCTGCACT
                           CCTCTCTGCACT
                           CGTCTCTAGACT
                           CATCACTTCACT
                           CATCGCTCAACT
                           CATCACTAGACT
                           CATCACTCGACT
                           CGTCCCTACACT
                           CTTCGCTTGACT
                           CTTCCCTGAACT
                           """
      greedyMotifSearchWithPseudocounts(dna, k, t) shouldBe expectedResult
    }
    scenario("interactive quizz") {
      val dna = dna"""
                GTTCAATGTTTGTCCACGATGAGTGCTAGGGTCATGGATCAAATGTTCAACATTATCAGGCGGAAAGAAGTACCCAGGTCGGGGGGAGGTCGATGCTCTACGAGCCCAAAGTTTCACTTACGGGTTCCGTAGCAAGCGAGTTGCACTAACCATCAA
                CCAGCCCCCAGGGCGTCCTTAACGAACAAATTAGCGCCGTCTGAAGTACGAGACAAGAAACCCAGTTGGGGCATTATCTATTATTGCTCCTGTTACCGTCCCTACCCGGAACGTTATCCGATTCATTCATGCTCACGAATAAGGTGTCAGGCGAAC
                CCGCTCCAGGTTAGATTCCCCTGGATACCCAGAGATTATGAGGATCATCAACCAACAGGTTATACCAGTAGCTACAGTTCCTTCCTACCCTTAGATGCTACGGGTCCTAATTTATCTGCGAGTGAGCAGCTATCAAGCGGCTAACCCAGATAGGAA
                TTGCACATTCGCCGGGTGACGAGTCTCCTTGCTCATTTTAGGACTGGAAGAGAGCTCAACAATACCATTTCGCCACTAGGCCCCTAATGGAACCCGCCGTGTCGGAATCACTGGCGTCCCCCCAGTTTGGCCTGACACAATGAACTGTCACATCTC
                GGACCAGTAAACACAGTGACGCTTGGCACATCGAAGAGTAGAACTGACAATGCACTTAGAGCTGATGCAGTTAAAGAGGTTGCAAGCTAAGCGGGGCAGTAGGAACATCGGTGGCTCATACAGCAAATTTACCCCAGGTAGGCCCTTAAACCTAGC
                CACTTGCCATTCCAAAACATTGCCGCGTATCCGCTGGCAAGATCGATTATTGCCGCGGTCCTCCGTCAAGGGTTATGGGACACTCGGGTTGGGAGATGATCCGCCCGCCCCAGGTCGGCTAGTTACCAAAGAATTGCGGTGCGACGGCCGACTGAA
                GAGCAGCATGAACTCACTCAGGCGCCCAGCTTGGAGTTGCAATCGCAATTACTAATGCCAGGTTCAAAAGAACACCTACCACGGGGGGCAAGCGTAAGTACCAGCCCCTACTAAGTTGGGTCCTGTGATGACCGGTTCCCCTCTGCATTAACAAAT
                TTGAAGAGGTCCCCCTACATTTAAGCAACAACCCGAAGGCGTGCATCGACTTTTAGGCTGAATCTGAGCACTGGGAAAACGCGAACCGGCGGTCCACCCAGCTTGGTGCCGCTTAAAAGATAGCCACAAAGCTACACGCCCCCCGCCTTAGAACCA
                TGCATGTAATTAGATCAACGTTTGATCCGAGTAGGACCCAGATAGGGCAGGTCTCATACGGAGACGAATGTCAGGGATTGCCGAACTACCCGCCTGAGTCTATGGAGGCTTTGAGGACCGGCATGCCTAGACTGACTGATTCGGCTACCGCCTTCT
                TTCTCGCTCAGGCAGGAACAGCGGTGCCAGACCACCATGAGAAGGTTTGGGGGTTATTTCTTCTCTTACATTAGGTCGGAGCAGGGTGCTTACCTCGCATCGGTACTTCTCGACTCCGTAGGGAAAGATTCCGGCCATCGTCCCCCCAGTTCGGGC
                GTAACTTAAGTTGCATGACGGGCCTCAGGGACCTCTCCCAGTTAGGGTACCTTCCGCCTAAAAGCGAAAATGCTGGTATGAGACACCTCCTTCTAGGAGCCGTATCCCAGGTTATACCGTTTAGGATAGCGGGAGTGGAGATCTCCCAGTGGGGTT
                GAGCCGAGCTTGAGTGACCGTGACAATGCGGTTGTCGGGTATTGGCCACCCAGGTGGGTACGATCGTCGATATAGTTCTGAGAAAAGTCGCGCCGCATCGAACGCAATTCGGAGTGTAACCGCAGTGTATAGCCCCGGGTTCGGCCGTTTGAAATT
                GACTTTTCGTATCCCAGCTGGGGATGAGTTATTATGGCCGTGTTCAACCGACGGAGAACTCGGCCCAGTGGGACAAAAGAAACGACGACCTAGCGGGCTTAACCACCTAACTGTAGTCAGGCATCCTCGTCGAATTGTCTGGTAAAGTCAGCTGAG
                ACTTGAGGCTATGCTTACTGGGATACGGTCGGCCGATCGGGATGAATAGGGATCACTGTAGAAGCTCCCTGTTCGGACGTTAGCGTTACTCGTGCGAGAATTAACGAGCCCAGCTGGGGTGAGAGAATGCGAAGCCCGCATTGCTCTACGGCCTCG
                ATCAAGGACAATCCTACACGCCCTGAAGATTGTGGCGTGTCGGTTGCTGTTCAGGAGCAGCGTGTGACCGGACGTTATTCATATCCCAGGTTGGCACGCTGACCAGGCATGAAACCCCAGTAGCTATCATCTGCTCGAGTAGCTGAGTCAGCTTGG
                TCTAGTGGCGCTAAGCTTCAATGAGTGTGTTTCGGGTCTCGTTTCCCGGCGTCGGTTTTTGTCCATGTTTGGTGCGTTAGGCTAAGCTTTTCGCTTAACTCTATCCGACCCAGGTCGGACTAGCCGACCTTGGAATCAAACACGCGGTGTAGTATA
                CTCAGGCTTCTCCGTTCGCCAGCTTTGGACCTTGCAGCTGTCATTCGGCTTCTACATCGCCGCTTTTGTGTGCCCAGGTTGGTCGCGAGACCCTAATTGTTATCGGGTCCTCCAACGCCTCCACTATGCAAACACCTCGTGCTGATAGGCTTAGGT
                ATCCCTTCCGGTCTCCCTTAGTACTAATCGCGTATCCCCAGTTAGGAACTATACCCGGGGAGGACAAAGATCGACTGCATATATACCCTCGTCGAACGACGATGCTAGTCCGAATAGTGTCCCGTCCGGTGTTGCCGGAATACACGCCAAGCGCCT
                AAATATCTCATTGAGATATGCACCGCATAGAACCGATATCATATTTCTCAGCGATCACGACCCAGGTGGGACTTGCTTAGAATATATCTCATCAAGTACCATCAGCGCGCACCGCGACGCTTAACAACACGACCGCACTAGTAGTAATACAATAAG
                AGTTACGACGGATGATAAGGAGAAAGCTGTACAGGATGCAGTTCTTCGTAATTGAGCTACTAATGGGAAAAAATTATAGCAACCTCAAATGCCTGACAGCACGTGGGCACGGATGTTCTAATGCTACGATATCCCGAAACTTATCCCAGATAGGAA
                ATTCTCTTACGACTACCGAAGCATCCCAGTTCGGGAGCATTCACTCCGTCGCGTATGTCAAATTCGAGGAACGGATTACAGACGGGACGCACGGCCGCATAGAACTTGCTTGTACGTCGCCTACCGGCCTCTCGAGCACTTCGAGGTCGCCCTATC
                AACGCACTATAACAGTACATGTGTAGCCGCTAGAGACGTTATGATCTGCTTCCTTAATAACGGGGCTCGAATGTCGTAATAGATCCGCCCTGCTATTTGTAAGGGTGCTTAATTCACCACCCCAGATAGGAAGAGGAGGGAAATGCGGTCAAGAGG
                TGTTCTCTGTCGTTGGATTAGTTGAGGGGGTCATTTCCCAGATGGGGTTAGTGAGCGGGGCGACTCTTCAAAGATCTCGGAAGCTGTCCGAGATTGCTCCCTTTTGAATCGCTAGAACAGTGCCACTATCTAGATAATATTACGCGAGCCTAATCG
                ACTGAATGCAAGGACGAGTGTTGGGACGCAACGCCGTGCCTCATAAGCTAGGCCACCGCTTACCACAGTGACCCTGTATGCACGGTAGACTATTTGCCCAGATCGGAGAGCTGCTGTTTCATTGGAGAAGCATTCCCTTGACCATTGATGATCGTC
                ACTTATCCAAACTTGTACTACGTACTGAGCCGGCCCCCCAGATGGGCGACGAGAGGCGCGCCGGAATCGACGTATGCCTAGCGTCGTTACGCATGAAAACGGGTATATTCAAGAAATGCTGTGCCGCGCGTCATGCATTGGGACGGGGTTACAACT
                """
      val k = 12
      val t = dna.length
      val result = greedyMotifSearchWithPseudocounts(dna, k, t)
      val expectedResult = dna"TACCCAGGTCGG AACCCAGTTGGG AACCCAGATAGG CCCCCAGTTTGG ACCCCAGGTAGG GCCCCAGGTCGG CGCCCAGCTTGG CACCCAGCTTGG GACCCAGATAGG CCCCCAGTTCGG CTCCCAGTTAGG CACCCAGGTGGG ATCCCAGCTGGG AGCCCAGCTGGG ATCCCAGGTTGG GACCCAGGTCGG TGCCCAGGTTGG TCCCCAGTTAGG GACCCAGGTGGG ATCCCAGATAGG ATCCCAGTTCGG ACCCCAGATAGG TTCCCAGATGGG TGCCCAGATCGG CCCCCAGATGGG"
      //println(result.mkString(" "))
      result shouldBe expectedResult
    }
  }

  feature("randomizedMotifSearch") {
    scenario("sample") {
      val dna = dna"""
                CGCCCCTCTCGGGGGTGTTCAGTAAACGGCCA
                GGGCGAGGTATGTGTAAGTGCCAAGGTGCCAG
                TAGTACCGAGACCGAAAGAAGTATACAGGCGT
                TAGATCAAGTTTCAGGTGCACGTCGGTGAACC
                AATCCACCAGCTCCACGTGCAATGTTGGCCTA
                """
      val k = 8
      val t = dna.length
      randomizedMotifSearch(dna, k, t, 10000) shouldBe dna"TCTCGGGG CCAAGGTG TACAGGCG TTCAGGTG TCCACGTG"
    }
    scenario("extra dataset") {
      val dna = dna"""
                ACTTATATCTAGAGTAAAGCCCTGATTCCATTGACGCGATCCCTACCTCCATCATACTCCACAGGTTCTTCAATAGAACATGGGGAAAACTGAGGTACACCAGGTCTAACGGAGATTTCTGGCACTAACTACCCAAAATCGAGTGATTGAACTGACTTATATCTAGAGT
                AAAGCCCTGATTCCATTGACGCGATCCCTACCTCCATCATACTCCACAGGTTCTTCAATAGAACATGGGGAAAACTGAGGTACACCAGGTCTAACGGAGATTTCTGGCACTAACTACCCAAAATCCTCTCGATCACCGACGAGTGATTGAACTGACTTATATCTAGAGT
                CACTCCCGTCCGTCTGACGCCAGGTGCTCTACCCCGCTGATTGTCTGGTACATAGCAGCCTATAGATCACCGATGCAGAAACACTTCGAGGCAGCCGATTTCGCTTATCACAACGTGACGGAATTTGATAAACCACGTACTCTAATACCGTCACGGGCCCATCAACGAA
                ACAAGAACTGGTGGGGAGACTATGACACTCTAGCGGTCGCATAAGGGCCGGAAACCAGGACAAATCGATAAGATGAAGCGGGGATATAAGCCTTATACTGCGACTGGTTCCTTATATTATTTAGCCCCGATTGATCACCGATTAAAATATTCTGCGGTTTTCGAGACGG
                TAACCACACCTAAAATTTTTCTTGGTGAGATGGACCCCCGCCGTAAATATCAGGATTAAATGTACGGATACCCATGACCCTCCAGTCATCTACCTTCCCGTGGTGGTCGCTCAGCCTTGTGCAGACCGAACTAGCACCTGTCACATACAATGTTGCCCGCATAGATCGT
                ATCCGACAGAGGCAGTGAATAAGGTTTCGTTTCCTCAGAGAGTAGAACTGCGTGTGACCTTGCCTTCACCGACATCCGTTTCCAATTGAGCTTTTCAGGACGTTTAGGTAACTGATTGTCATTGCAATTGTCCGGGGGATTTAGATGGCCGGGTACCTCTCGGACTATA
                CCTTGTTGCCACCGATTCGCGAGCAACATCGGAGTGCTCTGATTCACGGCGATGCTCCACGAAGAGGACCGCGGCACGACACGCCCTGTACCTACGTTTCTGGATATCCTCCGGCGAGTTAATAGAGCAATACGACCTGGTCGTCGAGATCGTGTATCTAGCCCTACCT
                ATAGGTTAACGAATCAGGAGAGTTAATTTTACCTAGCTAGAGCGGACGGTGCCTGGCTGTATTCGCGTTTGACTTTCGGGCTCGCTGATAACTTGTGATCACCTTTTACGCTTACTGGATCCAACGATGGATCAAAGTTGAGAATTTCTGTGCCTTGGGTGTGAGCTGT
                CTGACGAAAGGACGGGCGGTGTACTTAGTTTGGGGTAAAATAGTTGGTATAATTCTGTGCGACAGACATTTGGTCAGGCCATACTGCCATATCGTGATGTAACTATCCACACTACGTCATAGGCCCTTGTGATCAATTAAACGTTCCTCATGCCAGGCTATCTGTTTAA
                GGCTTCGCGTTTAAGGCTGGATTAAGTACTCCGCCTTGTGATCTGTGATCCTCCGACCTGTGATCAGCAAGATTGGAACCTAGGTAGGCGGCGGGTCTACGCTGGCCCACAATCGTGAGTCCCCCACTCCGTAGGTTGTGGAATTTATAGACCCGCAAGGGGCACCACT
                AGGATGACACCCAGGATGAATCTGGATTAGGAACACCAACCCGACATATTTGTTACCGCTGCAGCATTTCGCTCTTGGACGCGTAACCCGAGATCCGTCTCGCGATCGTCACGGATCGGGATTATGCAGGCAATACCTTGTGATCACTCCGCGCTTGGTTTTGCTAGCG
                ACATCTCTAGTCACTTTTATTGAGCAGGTGGGCGGATTCATGATCCGGCTCTGTCGTACGTCCAACCACGGTGACATGTTCGGAGCTGTCGCCGTGGAGCAGAGATACATCGGATCTATCAATTTTACTAAGAGCAACTAGCCACGACAAACTGTGATCACCGATTGGA
                AATTTGCGTATCTCTAGGACTCCCTCATACAAATCAAAGCTTGGATGGGTAAGATGCCGCAGCAGCAGGTATCTCATATTGGCTATTAAGAGCCAGGCCCTATGGCCTTAGTATCACCGATCAGACGTCGCATGAGCGGGCCCGTTGTCCTATCTCTTTAGCTGCCGCA
                GAAGTAAAGGGGTTCCACTGCGTAGAGCGTGCCCCTCTGGTGTGCCGTACTGTTATGGTGATACAGCTTCCTTATACCCCTCGTAAAGCGGCTAATGGTCCTAATGAATGCCCTTGTGAAATCCGAATCGCTTTACAATTGCGTTCGGCGGAATGCAGTCACCAGTGTT
                TACACTACGCGTTATTTACTTTTACTGAGTCCTTGTCGCCACCGAACGAGGATTGTTCATTGTATCCGGAGATTAGGAGTTCGCATCGCTGACACAGCCAGTTCGTAGCAAATACCGCTGGCCCTGGGCACTCCAGATCAGAACTACTAGCCCTAAACTCTATGACACA
                TTGGGTCTCGATCCCTCTATGTTAAGCTGTTCCGTGGAGAATCTCCTGGGTTTTATGATTTGAATGACGAGAATTGGGAAGTCGGGATGTTGTGATCACCGCCGTTCGCTTTCATAAATGAACCCCTTTTTTTCAGCAGACGGTGGCCTTTCCCTTTCATCATTATACA
                TTTCAAGTTACTACCGCCCTCTAGCGATAGAACTGAGGCAAATCATACACCGTGATCACCGACCCATGGAGTTTGACTCAGATTTACACTTTTAGGGGAACATGTTTGTCGGTCAGAGGTGTCAATTATTAGCAGATATCCCCCAACGCAGCGAGAGAGCACGGAGTGA
                GATCCATTACCCTACGATATGTATATAGCGCCCTAGTACGGCTTCTCCCTTGCAGACACGCAGGCGCTGTGCGCTATCGGCTTCCTCGGACATTCCTGGATATAAGTAACGGCGAACTGGCTATCACTACCGCCGCTCCTTAAGCCTTGGTTTCACCGACGATTGTCGT
                TAGTAGATTATTACCTGTGGACCGTTAGCTTCAAGACCGAAACGTTGGTGATGCTACTTAAATGTCAAGAGTTGCGAAGTTGGGCGAAGCACATCCGTACTCCCAAGTGGACGATCGATAGATCCATGGAGTTTCCATCCATCTTAATCCGCCCTTTGCATCACCGACG
                TACAAGGCACAAACGAGACCTGATCGAACGGTGCACGGTCGAGGCAGCGAGATAAATGTACATTGAGAGCACCTTGTGATTTACGACCTGCATCGAAGGTTTCTTGGCACCCACCTGTCGTCCGCCAGGGCAGAGCCGACATTATATGACGCTGATGTACGAAGCCCCT
                """
      val k = 15
      val t = dna.length
      randomizedMotifSearch(dna, k, t) shouldBe dna"""
                                                CATGGGGAAAACTGA
                                                CCTCTCGATCACCGA
                                                CCTATAGATCACCGA
                                                CCGATTGATCACCGA
                                                CCTTGTGCAGACCGA
                                                CCTTGCCTTCACCGA
                                                CCTTGTTGCCACCGA
                                                ACTTGTGATCACCTT
                                                CCTTGTGATCAATTA
                                                CCTTGTGATCTGTGA
                                                CCTTGTGATCACTCC
                                                AACTGTGATCACCGA
                                                CCTTAGTATCACCGA
                                                CCTTGTGAAATCCGA
                                                CCTTGTCGCCACCGA
                                                TGTTGTGATCACCGC
                                                CACCGTGATCACCGA
                                                CCTTGGTTTCACCGA
                                                CCTTTGCATCACCGA
                                                CCTTGTGATTTACGA
                                                """
    }
    scenario("interactive quiz") {
      val dna = dna"""
                CTCTTCGACGTGTACTCTCTTGCCCAAGCGGCGCACGAGTAGCATTTCGGTTAGTATCAAGAGCCGTCAGCGAGTGACCATACAAAACGCGACCCTCTATGCTCTCCGGGGTTAATGTTGCCAGACTGGTACCAGCTTTAATCGAAAAATTCTCTCTTCGACGTGTAC
                TCTCTTGCCCAAGCGGCGCACGAGTAGCGCCAATACGTCAGTCATTTCGGTTAGTATCAAGAGCCGTCAGCGAGTGACCATACAAAACGCGACCCTCTATGCTCTCCGGGGTTAATGTTGCCAGACTGGTACCAGCTTTAATCGAAAAATTCTCTCTTCGACGTGTAC
                CCTTGTCCCCATTGCTAGCATATGTTCGCTGTTGTCTCGCATGCCCGTGCAAGACCGAAGTCTTCCGGGCGAACCCTAAGTATCTATGAGGAGAGAAACAAATAGGGAATGCCTGCTCGTCAGTCAATGGTACCACGCCTTGTGGCTCTGTCAAGTGAGCTCAAGCAT
                GTTAGCGCCTGCTCGTCAGTCGATATTTTGCATGGGATCGCTGAAGTTTAAGAGACTGGCAAGTTAGGCAACGGATGCAAACACGATGCTCAAAACATTGTCGGCTACTTCGTGGGCCGATCAGGAGTTGTAACTGGTGTAAGATGAGACGTCCAGTGATGCGGACGC
                ACGAATGTTAGACGGTGTCAGCGCGAGGTATATCCCCGCAGTAGCTGATGTTCCTGCCTTGACGAACGTCCCGCCTAAGTCAACAAGCGATATCGAAAAGGGGAGTGAGCTACTAATAAACAATCCCGGTCCAGTGTATCCGTCATCGAATCTCGCCGAATTTTCGAG
                AGGAAGCAACCTCGACCACTGTGTACGCCTGGCAGAGGCAGCTAAGGGTTCACGTGTTTCGGGGTACATAAACCAGGAATGCCCCCAAACCTTCCTGTACCTCCAGTGCATAACCGGCCTTGACGTCTCGCCTAATGTAATCATGGATTGACCCCAACGGGTAAGTAC
                TGGCTGCGGTCGTAAGGGATTTAACCTTTGGCTCCATATGGACTCAGAGGGGGGCATCGAAACATTGGGGTCTCATACTGATATGGCATGACAGTCAAAAATGACTCAGGGTTTCAATACTAGGCGGGTCCGACCCATCCAATCAAATAGCCTTCTTGTCAGTCTGTA
                ATTACGTTCATGTGAAGAACACCCGGGTCGCAGATAGCGCTCGCCAAACTAAACGTGCAACCTCTCGGTCTACATTCGTACTTGCGCTAGCGAGCAATAGCGATCTCAGGTGCGGCGACTGCCTTGGAATCAGTCTACCGTCCGATGGTTTTATCTATATTGTTGTTG
                GCCGAGATTGGTACCGACTCAGGTATCGGAAAGTCACCTGTAATGGCGTCAACGGTGATCCCCTTGACGTCAGAAGATTGTTTAGTGACATGTACCGCGTTCCTCGTGGAATGATGGTGTCCAGCACCAAAATGGTTGCCACTAACTCTCCGACTTTCCTCTCTAGTA
                GGTCAGACTCCATGCATTTTATTGAACGTGTCTATGAATTTTGACGTCAGTCTTTTAAATCAAGGCTACGAAGGCAATATCCTGACCGACTCGTATTAACCCATTAATAACTAAGCGTCGAGCTGGTTCGCATATTTGCTAAATTTTGTGAGTAGCTCAACCCCTACC
                TTTTGATATCTTAAAAGATATGGGGATAGTAGGTAGCTATCCGCACACGGGCTTTTACTACGGACCTTAGTTCGGGTGAATGCCTTGACGTACCTCAATTGAGCAGTCCATAATTACCTAATCCTAGAAAGGTTGGTCATGGTGACAGCTCTTTTTTGCATGGCGAGG
                TGTGATAAGGGATCATAACGGGATCGGGAGACTTAAGCCTTAGTCGTTGATGGGTTCTCCGTAGAAAGACAAGATCAAAACCCCCCCGGACTTCGTTGCATGCGAGCTTGTATCAAACCCGCCTTGTGATCAGTCAGTATCTAACAGACTTACGACAGAACATTCTTT
                TTCTCCATCGAGTTTCGAGAAGATATGAGTTACCGCACATTACGCAACTTATTTGCATTCAGTCTTCCGCCCTTTAATCTAATTGAGCCCGCCTTAGTGTCAGTCTATTCTTACATTATACATTTTTTCACTAAGCTCCCGACCCATTCGTCTAGATCCGCAATAGAC
                TGGTGTGGTGCGGCCCCCTACGACCAGAGAGCCAATACGTCAGTCCTAACCTTCCGGCTTTGTTACGACGCGGACTGGCTGGAAGCAACGACCGTCCAACGTGATTCCCCACAACCTTCGTTGTTTGTCGTCATGTTTGGCGATCTAGCTCTGGGCTTCTGCCTGTCC
                TCCACGCCTTGACGTCATAGGCAGCTCCCTATTACTCTACTAAAGTTGGACTCCACAACTTATCAAGCGATTTATGTTCGCCAATATTAACTGGCCTAAGCTAGCATCACACCCATTGGACCATATTTAGTACGCCTAGAGACGCGTACAGTGATTAATAGGTCAGTT
                CCGTCCAAGGGTGGGTAGTGAAGCGAGACGTGTGGCACCTATTCACGTGCACACCGATACGGATCGAGCACTCTTAGCCGAACTGGGTCTGAAACTCGCCCAAAGAAACAGCTCCGGTTTGTTCGAACAGATAACTGATGAGGTCGGGCCTTGAACCCAGTCTGGCAA
                TAAATCTCTCTGCACAGACGTCAGTCGGTATTTGTGGAATTCTCGTACGTATAAATCTTACCTACTCCATGGGTCCTATTCTCACCCGGATGCAGGATGCATCAGAAGCTTCGCACAGTGTGTAGTCTTCCTTACACGTAGTCGATTCGACGCATCCGGAGAGTACAG
                ACGATGTCGTGGGATCATCTAGTAGATACGTGAACACCATGTAACGTCATGTCACTGCAGGCCCTGTGGGCGCTGTGTAGCCATGGTTGTGGGCGGGAATGCTCTCGATCGAGGCGCTTGACGTCAGTATCTGAAACAGAGCTTTCCGAACGATTAGCGGGCCACAGT
                GAAATTGAGTGAGGTGTCTGCCTTGACTCAAGTCTCGACGCACTTCAGTTATCCCCACCCCGCAAGAGGGGCATCAAGACTAGCGCGTAAAGGCGAACCATACGGACCGACATGCCCTTAGAAATTGTGCTGTGGACGAAGATCTGATCCCAACAGTTGATGTGGCAG
                ATTCGAGGATACTATTGGGCGAGCCCCACGAATCTCCCTCAAGTTTCTCTAATACAGATGGGCTTGCCAACATGAGGAGGTGAATCACCGCCGACTATCCCCTGGTAGTATTGACAAACTAGGACCGCTGCACCCGCCACAGTAAGGTGTGACGTCAGTCTAAAGAGT
                """
      val k = 15
      val t = dna.length
      val result = randomizedMotifSearch(dna, k, t)
      result shouldBe dna"""
                      GCATTTCGGTTAGTA
                      GCCAATACGTCAGTC
                      GCCTGCTCGTCAGTC
                      GCCTGCTCGTCAGTC
                      GCCTTGACGAACGTC
                      GCCTTGACGTCTCGC
                      GCCTTCTTGTCAGTC
                      GCCTTGGAATCAGTC
                      CCCTTGACGTCAGAA
                      ATTTTGACGTCAGTC
                      GCCTTGACGTACCTC
                      GCCTTGTGATCAGTC
                      GCCTTAGTGTCAGTC
                      GCCAATACGTCAGTC
                      GCCTTGACGTCATAG
                      GCCTTGAACCCAGTC
                      GCACAGACGTCAGTC
                      CGCTTGACGTCAGTA
                      GCCTTGACTCAAGTC
                      GGTGTGACGTCAGTC
                      """
    }
  }
  feature("gibbsSampler") {
    scenario("sample") {
      val dna = dna"""
                CGCCCCTCTCGGGGGTGTTCAGTAAACGGCCA
                GGGCGAGGTATGTGTAAGTGCCAAGGTGCCAG
                TAGTACCGAGACCGAAAGAAGTATACAGGCGT
                TAGATCAAGTTTCAGGTGCACGTCGGTGAACC
                AATCCACCAGCTCCACGTGCAATGTTGGCCTA
                """
      val k = 8
      val t = dna.length
      val N = 500
      val M = 100
      gibbsSampler(dna, k, t, N, M) shouldBe dna"TCTCGGGG CCAAGGTG TACAGGCG TTCAGGTG TCCACGTG"
    }
    scenario("interactive quiz") {
      val dna = dna"""
                TAGGTCGAAATCATCCGTAAGCAGTACTAAGGGCGAAACTTGCCTTCGAGTGGCCGTGAAAAGGTACTAGGTGTTACGGATGTGTCCGCTAAACACTAGGCGATTCCATTTTAATTCGTTTAGACTATCAGGATTAGATGTAACGCACAGATTGCACGAATATAGAACCAAGGCAGGCTATTGAACTTGCTTATCTATGAGCTTAAGCATGATTGACGGACAGCTTAGGCCATTGCTGCCATTATGGGGAAATATAAGGCGCCAAAGGTCGGAGGGCGAAGTCCGGGGAAGACGTCGTATTGTCCATGGAGGACCTTATTAGGTCGAAATCATC
                CGTAAGCAGTACTAAGGGCGAAACTTGCCTTCGAGTGGCCGTGAAAAGGTACTAGGTGTTACGGATGTGTCCGCTAAACACTAGGCGATTCCATTTTAAGGCCTGTTCCCCCATTTCGTTTAGACTATCAGGATTAGATGTAACGCACAGATTGCACGAATATAGAACCAAGGCAGGCTATTGAACTTGCTTATCTATGAGCTTAAGCATGATTGACGGACAGCTTAGGCCATTGCTGCCATTATGGGGAAATATAAGGCGCCAAAGGTCGGAGGGCGAAGTCCGGGGAAGACGTCGTATTGTCCATGGAGGACCTTATTAGGTCGAAATCATC
                TTTGTCGCAAAGCTATCGATCGTTCTTCGTTAAGACTCTGTTCAATCCGTTGCCCACCAGACGGTCTCTAGCTCCGTTTAAAGGCCTAGCGTACATTTAGATGTAGCCTCAGGAGTATAGTAACTACGACTCTATACAGTGGAGACCCCATCCTGGCGAATCTGCTGCCCTCATGTTTTTTATAGTCCTATGTCTCAGTGTTGGCCTCAAAGATATCGTTACATTGATCTTTACAGCTCGGTAGGCAAGGGGTCTTATTCGATCGCCGAGTCGGACCAACTTGAAGGGCAAAAACCCCCATACCTGACACCCTGCGTCCGTACAACCCTTCTCC
                GAGTTCGTACTAACGAAGGCAACGAGCCCCATGAGCGAGAGACGGGTCCACGCTTGTGTGGTTTAGCGGGCTGGTCGTATCACCCCGATTTCACAGCTTGGTCGATGAGCAGTTTGATACTCAAAATCGTGAGCGCTAGCGCGGTAGATTCTCCAATCGCCTTGATTCGGCATAAATCGCCTACTGTTTTTGGGGAGCCTTCCTACCAAGTGATTAATCCAGCTCAGTCCTCCGCGTACTCGTCAATCTGCCAGGCCGAGGCATATACACTAGCATTCATTTCGAGAAGACTCATCATGACTGAGGTGCATTCGTCCCATTTTTTAGTGAGGGG
                GGAACAGCATGCGTCCATGTATCGGTCGGAAGTCCGGGCGCGCCGAGTTGTTAAATAAAAGATGGCTATCGGAGCAACGAAGTGCCCCTGATTGTCTGAGCGCAGGGCACGCGTCGACGGCGCATCGCGGAGCTAGCGCGCGATATGCCTTCGAGTAAACTACATTGTAAATTCTACAGTGGGAGCTGACCACCCTCCAGCCATACAAGCGTTGTGGAGAAGATCATAACGTCATTGGTCATCGACATCTCACGTTCGTGTGGGGGAGTTACGGTGACTGGGTCTGTCGATGGTGTACTATAGAACTTCCCCCATCTGCCCTCAGGAGTTTCCG
                CCCTACAAAGTACATCCAGTGGGCATGGATGCGTATTTCAAAAGGATGTTCCTGCTTTTTTTATACCGTCGCGTGACTCCTGCAAATACGTGCAGCTGTGCTTGAACGAAGGATGTACGATGTTCCTCGCACCCGCCCTATCCTGGAAAGTATTACATCGAGTAGGTTTCCATGTTTGCCCGTCGCTGTCGCGAACCATGTGCACGATCGCAAGCCTCAGACCGTCAGAGTCTTGCCAGTCACCTTACGTGACAGTCCTAGAGGGCAAGCACCCCCATCGGAAGAATCTGGGCCCAATCAACACATGTTAAGTCCGTGATACTTATTTCGACCC
                TAATCCCCCCTAAGACAGAGGCTTGTTGCAAGTAGAGTTGCAACGCCTTTCTGTAATCTCGTTTACGGGTCGACGTCATGCGTTGAAAGTTTATCGGAAACTTCTTTGTTGGAGGTGGTGCGCAGCTTTCCAAATAGAGGCACTCTCCCCCATTAGCATTTACACCAATTCACGGAGAGGGTTCTACCAGATTAACTCACCACTTTAAATGTATCGGCCAGACGTATTGAGCTATTAAGGTTAACCTAGCGATCCTGACGCGAGTCATCCGGTTCGCCTGCACGAAGAAACATTGCGTGCTCCTCGATGCCTTTTCGGAGTCTAGTCGAAAAAG
                TCGACTGTTTAGTTGAAACATGAATAACTGCAACATGCAATGAGATATATGTTAGGGTTGGACAGCTGGATACTCTTCCTTCACGTTTGTGTTCGAAGGACTCCCAGAATATAAAAACAAGCTGCTGTTCTCAATCGTTTAGTTAACCAGCAAGACTTATAGAGTCACTGCATTCTAGGTGCCACTGAATGTACACAGCTTTCCTCATATTTTGGATAGCAAGGCAACTTTAGCCATTTTGAAAGGTGGCATGAAACCGATTCTCCCGTACCAACAGGACAATGGCAGTCTACATATTAAAGCCCAGACTCGCATCTCGGCTTACTGGGCTGTA
                AACGGAGCTATAGGTCCTTCTTCCGATGATAGACTTCGCGGTGAAAATTGCCTTTCTCTGCAGAGTCGAGGCTATTTTTCAGACTAGCTTCGTCTGAAGCTGCACGATGCGTAGGGATGTCATTTTGGATTGGGAGAAAAGGATAAGACAACAGGTGCTAGGGCCGTTCCCTTACAAAGGAATACGGATGACTGTAACAGCCTTTCGTTCCATGTCACCTCGTACGAGCAGTGATGTAATGTTTGTTTGCCTAAACGGTATGGTGTCGGAGGAGTCTGCTATGTCGCTACTGTTGTTGCCCTCGATCCAGGCAACTAGTCCCATTAAGGACTCC
                GGTTCTACAAGGCGTGCCCTTCGTTTGGCCGTTCAACCTCATGATTGGCAACTTCTTTCATAGAAAAGGGCCGGAAATATAGGATCCGAGAACCGGCGAGTGGGTTGGGTGGATCATTACCCGTACGTCTACGAACAGGGGTGGTTGAATAACTAGCTTAGTTCATCTGAAAGATTTGAGGGCGCCCAGCAATCGATTTACGCGGATGGACGCGTTTAGTGGGCTTAGCCGTATTCCTACGATCGCCAAATGTACGTCCGGTCTGCTCCTCGTGCACTCTGCTATTACGCGGGCAGATTAGCGTGTAACGCTATGCATCGCTTCGCTATGGTAC
                AGTTGCCAGGAGACACGCTGCCGAATCGGCGTGCCACCGCGCGAAGGCCTGGCACGGCGCGCCCAATTACCCACGTCAAGTCACGTTACTGGGGGGAGCAATAGTACGCCGATGCGGTCGGGGCCAACACTGCCGGTGGTAACTGAGGGAGAAGTCGGTGAGCAGACTGGCACTAACCGTTGAGTCATTCTGCAGAATCGGATTATTCATAGCACTCTGACAGTAGACAGCGGTGATCACCGGCGTATTCCCCCATCACTGGTCACTAGTCCTCACGGCTAGAGGGGTATGGAATAGCTTCCAGGGTCGCTAATCACCATTTATTCATGGGTTA
                GTGAGCCTGGGTCATACAAGTTAAGGTGCTGGCATAATCCCCCATGCAATGTCTGCTTGACTGCTGGAGCACGAGTCATAACATTTGAGCTGAAATTCCGCTAGGTTACTCCTATCAAATCCTCAGCTTTATATTCAATTATGTTTCCGCCTCTTAAAAGGCTAAACTCGTCGGTATTGCCGTAGCTCTACTCGCTTGTAAGCCTCATTCTACGATCTTACCGAGCGAAGTGTAGGGCCGGGGTTGGGTGTAAGCTCCGTGTTTGTCTACACGCTCTTCCCGTCTGACTGTACAACTGAATTCGCAGACACGTATCACAATTTGGGGCTGGTGA
                TAGAGGGAGAGGCCCGCTCGATCTGTTTCAATTCTGTCCCCTGAGTACGTGATAGTCTAGCACGTCACGTCTCGGTAGGTCGAATGCTCAAATGCTTTCTCTAGGTAATTCTTCCCTCGTAACCTTTAGGGAAAATACGTGCGTAAACTCCCCATGCGGCGATATCTGTCGTTGGTAAGTTCTCATAGCGCAAAGCATGAGCACTTCCCCCATAGAATGAGAGGGCACTCCCCGTGCAGCATAGGAGTGGTCTACTGAGGGCCGGTCATGTAGTACTAGCGTAATACGATTATGCTAGGCTCAGCCGAACCAGACCCTGTTACGGCAATTCGTG
                CTAAACGCAGGTGCGACGACTTTCCTAGCTATCCGATGGGGTGGCGCAGGCTCTCACGTTAAACTTGGTAGCGAGTAATGCCTATCTTGTGCCAATGTCCTGCAAACTGGGCCCGGTTCAACCGTGCGCTTAGTCTGGGCTGGAGTCTCGCGCCAACTAGTAGACCGCGGGCAACTTCCCTAGTCGTTCTCATCCACACCTCACAAACCGACCAATATTCTTTACTTCTGCTAGCGAGTCAACGCCATAGGAACCTTTGGAGGTGGATTATTGGAGCGCGCACGCGAAGCAAGTTTGAGCACATTATATCAGGCTCGATCTTCAGACCCCTTAA
                TGTATAGCACACACGAGGGCAACGAACCCCATGCTGCAGACAAGCTATGACTTCACTGGATAAAACCTAGTTATGGACCTATCAGGGTAGGCGGCCGTCAAATCCCGCTACTCGACATAGGCGAGAGAGGTGATTCCTTCCGGAGCTCCATGGGAATGTCAGTCAAAGCCTGGTGAAGCTCGTCAACGTGGTACGCCAACATCAGCTATTGACTGAGGCGGGTGAGCGTTCATATAATAGAACCGAAGTGTGGCGTCTGGGAGAGCACTCCCCACACCTCCGTGGTGCGAAAAACCGAACGTGATAGTTATATGAAAGTGTCCAATTGAAGAGA
                GAACGCGTTGCAACTTCCCCCGCGATGCATTAGGTTACTGTAGCAAATACCCGATAGCCACGCTCAGCAGTGGTTAATTCAATATAGTTATAAGCTGGCTTTACGAGACGCCCGAACAGTTTCGAGGCAGCGCGCGTGCAACAGACTCGTTTATATCCTGTGAAACGAATCTAGAAGGACGTGGTGTATGTCATTAGAGCGGAACCTGGTAGTCACAGGTTACGTTCACACCAAGGTCAACTGGGCCTTGTCGCCGCGGAGATGGGGTGTAGTATAAACATCACTATTCTCTAGGGTGGAAGGGTGGAGAAGGTCAGAGCACGGCCGAGTTCTA
                CTATGTGGTGCGCGTGGACCGCTTCTAGCAGCTAGAGTATAGATCATCCGACTTTAACTTAAAACGCAAATTTGCATTGACGTCTGTCTACAGGCGTTTTCAGGTGATGGGCGCTACCTAAACTTTGTCGGCTTTCCAAAAGCAATCATTAAACATGTCGCACTGGCAACTTCCCCTTGGATTGCTGGTCGCGTACGCTAGGGACGTGGACCATCCTCTCTTGTGAGTTCTACTGATGGTCGGGGCAGTGCAGATTAGACCGTAGTTTGAGGGATATGGTGCACCCAATTCCCCTACCTTGGCCGAAAGACTTAATCAGCCGTCGGCTAACATT
                ACCGGCGCAACGATCGACCATATTACCCTTTCCCGATTATGGCAGCGAACACAGGGGGGTACAATGCACGTACTCGGAGCGGCAGAGTCTGATTTTTAAAAACGATGTGCTACTGCATAATAGGCAAACCTGTTACATCCGGGGGCCAGCCCCATAATTTTTAAAGTGTGTATAAAAGGCCTGACACTGGCGCACGGCGGACCAAGCTTTCGGTGGCAACTTCCGTAATTGACGAAACGTGTATGGGGTAATATTGCGCCTGCCTATCTCCTGGGCTCGAATCGAAGACTACGCACTTAATGTCGGACCGTCGGAAAGTTCTGCCGAGCGTAAG
                CCCACAACGCATTGTAGTGTTCGTACGGTAGTGGACGAATATCTTCCGTCCGTCAGCCCGAAGTAGTTTATTGCCCAGCCGGGCGTAAGTGGTAGACTTAGCTGAAGTCTGCCTGCGCGCGGGCACCGGTTTCCGGGAAATAATATTTGGAACTTAAAGGAGGTCCAAGCTAGTGACTCAACTTCCCCCAACGCCAGACCCTGTGGGGCATTAGCCATTTCCACGCTAACCTATGGCCAGCTCGCTGTAGAAAGTTAATAGCAGCGCCTTATCGATCTCTGTTCGGCAGCGGGAAACCCTGTTGGGAAAGACACATAGCAAGCTCTGTGGTGGT
                GTACTGGTAACAGTGGGTCCGGTGCTCGCTCGAGGCCTGCAGTGCTCCGTGGGCTAAGTCTATTACGTATAGTGCTTCACATGCATATTCCGCTTATAAGCGGGGTGGGCCAGGTTATGCGGGGGGGTAGCGGTGGAGCCAGTTTCATAATCACTGCAAAAGCAGACAGCCGTAGTTTTTCGGTCGCAGAATTTACCTCATGGGACAAATGCAAGTCAGGGATGGGGCCCCAAGCTTGATTGATGGTGGTCCGCTCCATTGCAGGCATCAGCGGGAGCCTTCCCCCATGTCAGAAGGTTCCCTCTGAAACATCTATTCATCTTTACTACGTAGC
                """
      val k = 15
      val t = dna.length
      val N = 2000
      val M = 100
      val result = gibbsSampler(dna, k, t, N, M)
      //println(result.mkString("\n"))
      result shouldBe dna"""
                      GACAGCTTAGGCCAT
                      GGCCTGTTCCCCCAT
                      GGCAAAAACCCCCAT
                      GGCAACGAGCCCCAT
                      TAGAACTTCCCCCAT
                      GGCAAGCACCCCCAT
                      GGCACTCTCCCCCAT
                      GGCAACTTTAGCCAT
                      GGCAACTAGTCCCAT
                      GGCAACTTCTTTCAT
                      GGCGTATTCCCCCAT
                      GGCATAATCCCCCAT
                      GAGCACTTCCCCCAT
                      GGCAACTTCCCTAGT
                      GGCAACGAACCCCAT
                      TGCAACTTCCCCCGC
                      GGCAACTTCCCCTTG
                      GGCAACTTCCGTAAT
                      CTCAACTTCCCCCAA
                      GGAGCCTTCCCCCAT
                      """
    }
  }
}